import type { BluffPrompt, ContentPack } from '@hpg/shared'

const p = (id: string, question: string, answer: string): BluffPrompt => ({ id, question, answer })

const more = (prefix: string, rows: ReadonlyArray<readonly [string, string]>): BluffPrompt[] =>
  rows.map(([question, answer], index) => p(`${prefix}-${index + 11}`, question, answer))

/** Family tier — 100 kid-safe trivia prompts and surprising facts. */
export const bluffFamily: ContentPack<BluffPrompt> = {
  id: 'bluff-family-v1',
  game: 'bluff-battle',
  tone: 'family',
  locale: 'en',
  prompts: [
    p('blf-fam-1', 'Flamingos get their pink color from pigments called…', 'Carotenoids'),
    p('blf-fam-2', 'A baby kangaroo is called a…', 'A joey'),
    p('blf-fam-3', 'The only mammal that can truly fly is the…', 'Bat'),
    p('blf-fam-4', 'Bananas grow pointing…', 'Upward'),
    p('blf-fam-5', 'The rasping, tongue-like feeding organ of a snail is called a…', 'Radula'),
    p('blf-fam-6', 'The dot over a lowercase i is called a…', 'Tittle'),
    p('blf-fam-7', 'Octopuses have this many hearts…', 'Three'),
    p('blf-fam-8', 'The Hawaiian pizza was invented in…', 'Canada'),
    p('blf-fam-9', 'A pug is a breed of…', 'Dog'),
    p('blf-fam-10', 'Bees store honey in the wax cells of a…', 'Honeycomb'),
    ...more('blf-fam', [
      ['The largest planet in our solar system is…', 'Jupiter'],
      ['The planet known for its prominent rings is…', 'Saturn'],
      ['The closest star to Earth is…', 'The Sun'],
      ['Water freezes at this temperature on the Celsius scale…', '0 degrees'],
      ['The chemical symbol for gold is…', 'Au'],
      ['The hardest natural substance is…', 'Diamond'],
      ['The process plants use to turn light into food is…', 'Photosynthesis'],
      ['The gas humans need to breathe is…', 'Oxygen'],
      ['The center of an atom is called the…', 'Nucleus'],
      ['An animal with a backbone is called a…', 'Vertebrate'],
      ['The largest living animal is the…', 'Blue whale'],
      ['The fastest land animal is the…', 'Cheetah'],
      ['A caterpillar becomes a butterfly inside a…', 'Chrysalis'],
      ['A frog begins life as a…', 'Tadpole'],
      ['The egg-laying mammal with a duck-like bill is the…', 'Platypus'],
      ['A spider has this many legs…', 'Eight'],
      ['An insect has this many legs…', 'Six'],
      ['The black-and-white bear native to China is the…', 'Giant panda'],
      ['The tallest living land animal is the…', 'Giraffe'],
      ['The bird whose name is also used for a construction crane is the…', 'Crane'],
      ['The largest ocean on Earth is the…', 'Pacific Ocean'],
      ['The river that flows through Egypt and empties into the Mediterranean is the…', 'Nile'],
      ['The continent at the South Pole is…', 'Antarctica'],
      ['The capital of Japan is…', 'Tokyo'],
      ['The country shaped like a boot is…', 'Italy'],
      ['The Great Barrier Reef lies off the coast of which Australian state?', 'Queensland'],
      ['Mount Everest belongs to this mountain range…', 'The Himalayas'],
      ['The imaginary line dividing Earth into northern and southern halves is the…', 'Equator'],
      ['The smallest continent by land area is…', 'Australia'],
      ['The sea between Europe and Africa is the…', 'Mediterranean Sea'],
      ['A word with the opposite meaning of another word is an…', 'Antonym'],
      ['A word that imitates a sound, such as buzz, is an example of…', 'Onomatopoeia'],
      ['A sentence that asks a question ends with a…', 'Question mark'],
      ['The plural of mouse, referring to the animal, is…', 'Mice'],
      ['The first letter of the Greek alphabet is…', 'Alpha'],
      ['The Roman numeral X represents…', 'Ten'],
      ['A shape with eight sides is an…', 'Octagon'],
      ['A triangle with three equal sides is…', 'Equilateral'],
      ['The result of multiplying numbers is called the…', 'Product'],
      ['One thousand meters make one…', 'Kilometer'],
      ['The instrument used to measure temperature is a…', 'Thermometer'],
      ['The force that pulls objects toward Earth is…', 'Gravity'],
      ['Light travels faster than…', 'Sound'],
      ['The solid form of water is…', 'Ice'],
      ['Molten rock beneath Earth’s surface is called…', 'Magma'],
      ['A scientist who studies weather is a…', 'Meteorologist'],
      ['The layer of gases surrounding Earth is the…', 'Atmosphere'],
      ['Earth takes about this long to orbit the Sun…', 'One year'],
      ['The Moon’s gravity is the main cause of ocean…', 'Tides'],
      ['An arc of colors formed when sunlight meets water droplets is a…', 'Rainbow'],
      ['The ancient Egyptians wrote using picture symbols called…', 'Hieroglyphs'],
      ['The Olympic Games began in ancient…', 'Greece'],
      [
        'The printing press associated with movable type in Europe was developed by…',
        'Johannes Gutenberg',
      ],
      ['The first person to walk on the Moon was…', 'Neil Armstrong'],
      ['The ship that carried the Pilgrims to North America in 1620 was the…', 'Mayflower'],
      ['The famous bell in the Elizabeth Tower in London is nicknamed…', 'Big Ben'],
      ['The city buried by Mount Vesuvius in AD 79 was…', 'Pompeii'],
      ['The first U.S. president was…', 'George Washington'],
      ['The medieval defensive ditch around a castle is a…', 'Moat'],
      ['A person who studies fossils is a…', 'Paleontologist'],
      ['The wooden puppet whose nose grows when he lies is…', 'Pinocchio'],
      ['The author of Charlie and the Chocolate Factory was…', 'Roald Dahl'],
      ['The fairy-tale girl who loses a glass slipper is…', 'Cinderella'],
      ['The bear who loves honey in A. A. Milne’s stories is…', 'Winnie-the-Pooh'],
      ['The fictional school attended by Harry Potter is…', 'Hogwarts'],
      ['The superhero whose home planet is Krypton is…', 'Superman'],
      ['The author who created the wooden boy Pinocchio was…', 'Carlo Collodi'],
      ['The author of The Cat in the Hat was…', 'Dr. Seuss'],
      ['Sherlock Holmes lives at this fictional London address…', '221B Baker Street'],
      ['The lion in The Lion, the Witch and the Wardrobe is named…', 'Aslan'],
      ['A standard modern piano has this many keys…', '88'],
      ['In standard guitar tuning, the lowest-pitched string is…', 'Low E'],
      ['The family of instruments that includes trumpet and trombone is…', 'Brass'],
      ['A person who leads an orchestra is the…', 'Conductor'],
      ['The dance associated with a tutu and pointe shoes is…', 'Ballet'],
      ['Red and blue paint combine to make…', 'Purple'],
      ['A portrait is a picture primarily of a…', 'Person'],
      ['The primary colors in traditional paint mixing are red, yellow, and…', 'Blue'],
      ['The musical symbol that indicates silence is a…', 'Rest'],
      ['A story’s main character is its…', 'Protagonist'],
      ['The sport played at Wimbledon is…', 'Tennis'],
      ['A touchdown in American football is worth…', 'Six points'],
      ['A baseball team fields this many players at a time…', 'Nine'],
      ['The piece that must be protected in chess is the…', 'King'],
      ['The Olympic symbol contains this many rings…', 'Five'],
      ['In bowling, knocking down all ten pins with one ball is a…', 'Strike'],
      ['The sport that uses a shuttlecock is…', 'Badminton'],
      ['A marathon is approximately this many kilometers long…', '42.195'],
      ['The card suit shaped like a three-leaf plant is…', 'Clubs'],
      ['The board game featuring Boardwalk and Park Place is…', 'Monopoly'],
    ]),
  ],
}

/** Friends tier — 100 offbeat factual prompts for a general audience. */
export const bluffFriends: ContentPack<BluffPrompt> = {
  id: 'bluff-friends-v1',
  game: 'bluff-battle',
  tone: 'friends',
  locale: 'en',
  prompts: [
    p(
      'blf-fri-1',
      'Swiss welfare rules require social contact for which small pet of the cavy family?',
      'Guinea pig',
    ),
    p('blf-fri-2', 'The fear of being without access to a mobile phone is called…', 'Nomophobia'),
    p('blf-fri-3', 'The first thing ever sold on eBay was a broken…', 'Laser pointer'),
    p('blf-fri-4', 'Wombats poop in this shape…', 'Cubes'),
    p('blf-fri-5', 'A word that reads the same forward and backward is a…', 'Palindrome'),
    p('blf-fri-6', 'Japan’s high-speed passenger trains are commonly called…', 'Shinkansen'),
    p('blf-fri-7', 'Orion is a named…', 'Constellation'),
    p(
      'blf-fri-8',
      'Before alarm clocks, "knocker-uppers" woke people by…',
      'Tapping windows with sticks',
    ),
    p('blf-fri-9', 'The symbol made by joining two or more letters is a…', 'Ligature'),
    p('blf-fri-10', 'A cow-bison hybrid is called a…', 'Beefalo'),
    ...more('blf-fri', [
      ['The tiny pocket on jeans was originally designed to hold a…', 'Pocket watch'],
      ['The plastic tip at the end of a shoelace is an…', 'Aglet'],
      ['The groove between the nose and upper lip is the…', 'Philtrum'],
      ['The smell produced when rain hits dry soil is called…', 'Petrichor'],
      ['The rumbling sound from an empty stomach is called…', 'Borborygmus'],
      ['The symbol & is called an…', 'Ampersand'],
      ['The space between eyebrows is the…', 'Glabella'],
      ['The white crescent at the base of a fingernail is the…', 'Lunula'],
      ['The punctuation mark showing omitted letters in “can’t” is an…', 'Apostrophe'],
      ['A word formed from initials, such as NASA, is an…', 'Acronym'],
      ['Scotland’s national animal is the…', 'Unicorn'],
      ['The Canary Islands were named after…', 'Dogs'],
      ['The country with a cedar tree on its flag is…', 'Lebanon'],
      ['The capital city divided by the Danube into Buda and Pest is…', 'Budapest'],
      ['The only national flag that is not quadrilateral belongs to…', 'Nepal'],
      ['The ancient city of Petra is in modern-day…', 'Jordan'],
      ['The republic centered on Mount Titano and surrounded by Italy is…', 'San Marino'],
      ['The U.S. state whose postal abbreviation is HI is…', 'Hawaii'],
      ['The strait separating Spain from Morocco is the…', 'Strait of Gibraltar'],
      ['The European capital on the River Liffey is…', 'Dublin'],
      ['The animal whose fingerprints can resemble human fingerprints is the…', 'Koala'],
      ['The flightless bird that is a national symbol of New Zealand is the…', 'Kiwi'],
      ['A group of crows is traditionally called a…', 'Murder'],
      ['The mammal covered in protective scales is the…', 'Pangolin'],
      ['The axolotl is native to the lake system around…', 'Mexico City'],
      ['Sea otters use rocks as…', 'Tools'],
      ['The narwhal’s tusk is actually an elongated…', 'Tooth'],
      ['The largest toothed predator is the…', 'Sperm whale'],
      ['The bird associated with delivering babies in folklore is the…', 'Stork'],
      ['The animal that produces pearls is commonly an…', 'Oyster'],
      ['The metal that is liquid at standard room temperature is…', 'Mercury'],
      ['The element whose chemical symbol is K is…', 'Potassium'],
      ['Pure water at 25°C is classified on the pH scale as…', 'Neutral'],
      ['The mineral used as the “lead” in pencils is…', 'Graphite'],
      ['Which planet takes about 243 Earth days for one sidereal rotation?', 'Venus'],
      ['The galaxy containing our solar system is the…', 'Milky Way'],
      [
        'The boundary around a black hole beyond which light cannot escape is the…',
        'Event horizon',
      ],
      ['The SI unit of electric current is the…', 'Ampere'],
      ['The branch of science that studies fungi is…', 'Mycology'],
      ['The scale used to rank mineral hardness is the…', 'Mohs scale'],
      ['The shortest war on record was fought between Britain and…', 'Zanzibar'],
      ['The ancient Roman city preserved by volcanic ash alongside Pompeii is…', 'Herculaneum'],
      ['The first modern Olympic Games were held in…', 'Athens'],
      ['The document sealed in 1215 limiting the English king’s power was…', 'Magna Carta'],
      ['The artist who painted The Persistence of Memory was…', 'Salvador Dalí'],
      [
        'The composer who continued writing music after losing much of his hearing was…',
        'Ludwig van Beethoven',
      ],
      [
        'The archaeological object that helped scholars decipher Egyptian hieroglyphs was the…',
        'Rosetta Stone',
      ],
      ['The city once called Constantinople is now…', 'Istanbul'],
      ['The empire ruled from Cusco before the Spanish conquest was the…', 'Inca Empire'],
      ['The first woman to win a Nobel Prize was…', 'Marie Curie'],
      ['The novel featuring Elizabeth Bennet and Fitzwilliam Darcy is…', 'Pride and Prejudice'],
      [
        'The fictional detective created by Agatha Christie with a famous mustache is…',
        'Hercule Poirot',
      ],
      ['The author who created Middle-earth was…', 'J. R. R. Tolkien'],
      ['The novel featuring the whale Moby Dick is narrated by…', 'Ishmael'],
      ['The playwright who wrote Waiting for Godot was…', 'Samuel Beckett'],
      ['The dystopian novel featuring Big Brother is…', 'Nineteen Eighty-Four'],
      ['The fictional count who lives in Transylvania is…', 'Dracula'],
      ['The poet traditionally credited with The Odyssey is…', 'Homer'],
      ['The author of One Hundred Years of Solitude was…', 'Gabriel García Márquez'],
      ['The raven in Edgar Allan Poe’s poem repeatedly says…', 'Nevermore'],
      ['The cocktail traditionally made with gin and dry vermouth is a…', 'Martini'],
      ['The spirit used in a classic mojito is…', 'Rum'],
      ['The chickpea-based dip containing tahini is…', 'Hummus'],
      ['The Japanese seasoning paste made from fermented soybeans is…', 'Miso'],
      ['The cheese traditionally used in a Greek salad is…', 'Feta'],
      ['The pastry used for baklava is…', 'Phyllo'],
      ['The fruit dried to make a prune is a…', 'Plum'],
      ['The herb that gives traditional pesto its green color is…', 'Basil'],
      ['The Spanish rice dish traditionally cooked in a wide shallow pan is…', 'Paella'],
      ['The espresso drink named for the brown robes of Capuchin friars is a…', 'Cappuccino'],
      ['The first feature-length computer-animated film was…', 'Toy Story'],
      ['The director of Jaws and E.T. was…', 'Steven Spielberg'],
      [
        'The actor who portrayed the title character in the 1978 film Superman was…',
        'Christopher Reeve',
      ],
      ['The fictional newspaper where Clark Kent works is the…', 'Daily Planet'],
      ['The TV series set in the paper company Dunder Mifflin is…', 'The Office'],
      ['The singer born Farrokh Bulsara was…', 'Freddie Mercury'],
      ['The Beatles’ core drummer during their recording career was…', 'Ringo Starr'],
      ['The musical interval spanning eight scale notes is an…', 'Octave'],
      ['The filmmaker who directed Spirited Away is…', 'Hayao Miyazaki'],
      ['The arcade character who eats dots while avoiding ghosts is…', 'Pac-Man'],
      ['The chess piece that moves in an L shape is the…', 'Knight'],
      ['The maximum score with three darts in standard darts is…', '180'],
      ['The term for three goals by one player in a game is a…', 'Hat trick'],
      ['The billiards ball numbered eight is traditionally…', 'Black'],
      ['The inventor who patented The Landlord’s Game was…', 'Elizabeth Magie'],
      ['The video-game plumber whose brother is Luigi is…', 'Mario'],
      ['In poker, five cards of the same suit form a…', 'Flush'],
      ['The sport in which players sweep ice ahead of a stone is…', 'Curling'],
      ['The central target in archery is the…', 'Bullseye'],
      ['The board game with letter tiles and triple-word scores is…', 'Scrabble'],
    ]),
  ],
}

/** Spicy tier — 100 playful dating, romance, and social-custom facts for adults. */
export const bluffSpicy: ContentPack<BluffPrompt> = {
  id: 'bluff-spicy-v1',
  game: 'bluff-battle',
  tone: 'spicy',
  locale: 'en',
  prompts: [
    p(
      'blf-spi-1',
      'The involuntary reddening of the face from embarrassment is called…',
      'Blushing',
    ),
    p('blf-spi-2', 'A breach of accepted social etiquette is called a…', 'Faux pas'),
    p('blf-spi-3', 'Overestimating how much other people notice you is the…', 'Spotlight effect'),
    p('blf-spi-4', 'A card once used to record reserved ballroom partners was a…', 'Dance card'),
    p('blf-spi-5', 'An expression of regret for a mistake is an…', 'Apology'),
    p('blf-spi-6', 'A performance created without a prepared script is…', 'Improvisation'),
    p('blf-spi-7', 'Delivering comedy without visible emotion is called…', 'Deadpan'),
    p('blf-spi-8', 'The punctuation mark often used to show words trailing off is an…', 'Ellipsis'),
    p('blf-spi-9', 'A humorous imitation of a recognizable work or style is a…', 'Parody'),
    p('blf-spi-10', 'Speed dating was invented by a…', 'Rabbi'),
    ...more('blf-spi', [
      ['The matchmaker in the musical Fiddler on the Roof is…', 'Yente'],
      ['Saturday Night Live premiered in this year…', '1975'],
      ['The sitcom whose friends gather at Central Perk is…', 'Friends'],
      ['The Roman love god whose Greek counterpart is Eros is…', 'Cupid'],
      ['The comic actor who co-created and portrayed Mr. Bean is…', 'Rowan Atkinson'],
      ['Carrie Bradshaw’s signature pink cocktail is the…', 'Cosmopolitan'],
      ['The dating acronym DTR expands to…', 'Define the relationship'],
      ['Tequila, orange liqueur, and lime form a classic…', 'Margarita'],
      ['Robbie Hart in The Wedding Singer is played by…', 'Adam Sandler'],
      ['The 1990 film featuring Vivian Ward is…', 'Pretty Woman'],
      ['Valentine’s Day is celebrated on…', 'February 14'],
      ['The ancient festival called Lupercalia was celebrated in…', 'Rome'],
      ['The saint whose feast day became associated with romantic love is…', 'Saint Valentine'],
      ['In Wales, lovers traditionally exchanged carved wooden…', 'Love spoons'],
      ['The Welsh celebration of lovers on January 25 honors…', 'Saint Dwynwen'],
      ['In Japan, the holiday one month after Valentine’s Day is…', 'White Day'],
      ['Finland calls Valentine’s Day Ystävänpäivä, meaning…', 'Friend’s Day'],
      ['A line spoken to the audience but unheard by other characters is an…', 'Aside'],
      ['The Paris bridge famous for visitors attaching love locks is the…', 'Pont des Arts'],
      ['The Indian monument built by Shah Jahan in memory of Mumtaz Mahal is the…', 'Taj Mahal'],
      [
        'The deli used for the famous lunch scene in When Harry Met Sally… is…',
        'Katz’s Delicatessen',
      ],
      ['10 Things I Hate About You adapts Shakespeare’s…', 'The Taming of the Shrew'],
      ['Clueless is loosely based on which Jane Austen novel?', 'Emma'],
      ['The leads in You’ve Got Mail first connect through…', 'Email'],
      ['Margaret Tate in The Proposal is played by…', 'Sandra Bullock'],
      ['Rachel Chu teaches this subject in Crazy Rich Asians…', 'Economics'],
      [
        'Andie Anderson writes for this fictional magazine in How to Lose a Guy in 10 Days…',
        'Composure',
      ],
      ['Lucy Whitmore in 50 First Dates is played by…', 'Drew Barrymore'],
      ['The title matchmaker in Hitch is played by…', 'Will Smith'],
      ['A charming first encounter in romantic fiction is called a…', 'Meet-cute'],
      ['Michael Scott co-hosts The Office’s “Dinner Party” with…', 'Jan Levinson'],
      ['Laney Boggs is the makeover subject in the 1999 film…', 'She’s All That'],
      ['Ben Wyatt eventually marries this Parks and Recreation character…', 'Leslie Knope'],
      ['Jake Peralta proposes to this detective in Brooklyn Nine-Nine…', 'Amy Santiago'],
      ['David Rose eventually marries this Schitt’s Creek character…', 'Patrick Brewer'],
      ['The title “New Girl” who moves into the loft is…', 'Jess Day'],
      ['Ilsa Lund in Casablanca is played by…', 'Ingrid Bergman'],
      ['The Seinfeld gang often meets at this fictional café…', 'Monk’s Café'],
      ['The missing groom in The Hangover is…', 'Doug'],
      ['Annie in Bridesmaids is played by…', 'Kristen Wiig'],
      ['The 2000 film High Fidelity is set in…', 'Chicago'],
      ['The actor who portrays Mrs. Doubtfire is…', 'Robin Williams'],
      ['The fear of public speaking is called…', 'Glossophobia'],
      ['The comedian associated with the “seven dirty words” routine is…', 'George Carlin'],
      ['Contestants first meet in isolated rooms on Love Is Blind called…', 'Pods'],
      ['The HBO comedy-drama centered on Issa Dee is…', 'Insecure'],
      ['The 1994 romantic comedy featuring Charles and Carrie is…', 'Four Weddings and a Funeral'],
      [
        'The romantic comedy in which Julia Roberts plays bookstore visitor Anna Scott is…',
        'Notting Hill',
      ],
      ['The film featuring the pottery scene between Sam and Molly is…', 'Ghost'],
      ['The film in which Buttercup calls Westley her true love is…', 'The Princess Bride'],
      ['The film featuring Noah and Allie is…', 'The Notebook'],
      [
        'The romantic comedy built around a radio call from “Sleepless in Seattle” is…',
        'Sleepless in Seattle',
      ],
      ['The actress who played Bridget Jones in the 2001 film was…', 'Renée Zellweger'],
      ['The actor who played Mr. Darcy in the 1995 BBC Pride and Prejudice was…', 'Colin Firth'],
      ['Lloyd Dobler holds a boombox overhead in…', 'Say Anything…'],
      ['Ted Mosby narrates his search for love in…', 'How I Met Your Mother'],
      ['Carrie Bradshaw writes her column for the fictional…', 'New York Star'],
      ['Tim Lake discovers he can revisit moments of his life in…', 'About Time'],
      ['Jane Nichols has served as a bridesmaid 27 times in…', '27 Dresses'],
      ['A private meeting between lovers can be called a…', 'Tryst'],
      ['Toula Portokalos is the central character of…', 'My Big Fat Greek Wedding'],
      ['Mary Fiore plans weddings in the film…', 'The Wedding Planner'],
      ['Julianne Potter tries to stop Michael’s wedding in…', 'My Best Friend’s Wedding'],
      ['Elle Woods’s Chihuahua in Legally Blonde is named…', 'Bruiser'],
      ['The anonymous gossip writer in Bridgerton signs as…', 'Lady Whistledown'],
      ['The Bachelor traditionally hands out these flowers at rose ceremonies…', 'Roses'],
      ['The dating app represented by a flame logo is…', 'Tinder'],
      ['A message indicator showing that the recipient opened it is a…', 'Read receipt'],
      ['The Japanese word koi is also the name of a type of…', 'Carp'],
      ['Moving a dating profile aside with a finger gesture is a…', 'Swipe'],
      ['A restaurant booking held for a particular time is a…', 'Reservation'],
      [
        'The person who traditionally gives a wedding toast and supports the groom is the…',
        'Best man',
      ],
      ['Donna Sheridan in Mamma Mia! is played by…', 'Meryl Streep'],
      ['The trip taken by newlyweds after a wedding is the…', 'Honeymoon'],
      ['The dance traditionally opened by newlyweds at a reception is the…', 'First dance'],
      ['The small flowers worn on a suit lapel at a wedding form a…', 'Boutonniere'],
      ['The flowers carried by a bride form a…', 'Bouquet'],
      ['The Emcee in the 1972 film Cabaret is played by…', 'Joel Grey'],
      ['Brad’s fiancée in The Rocky Horror Picture Show is…', 'Janet'],
      ['The cabaret star in Moulin Rouge! is named…', 'Satine'],
      ['The fictional bar in Cheers is located in…', 'Boston'],
      ['The nightclub Studio 54 was located in…', 'New York City'],
      ['Jacob Palmer in Crazy, Stupid, Love is played by…', 'Ryan Gosling'],
      ['The disco in Saturday Night Fever is called…', '2001 Odyssey'],
      ['James Bond orders his martini shaken, not…', 'Stirred'],
      ['The resort in Dirty Dancing is named…', 'Kellerman’s'],
      ['Dalton in the 1989 film Road House is played by…', 'Patrick Swayze'],
      ['Sara Johnson moves to Chicago in the dance romance…', 'Save the Last Dance'],
      ['Frank Slade performs a tango in this film…', 'Scent of a Woman'],
      ['Iris and Amanda exchange homes in the romantic comedy…', 'The Holiday'],
    ]),
  ],
}
