import type { ContentPack, ImposterPrompt } from '@hpg/shared'

const p = (id: string, word: string, category: string): ImposterPrompt => ({ id, word, category })

const more = (prefix: string, rows: ReadonlyArray<readonly [string, string]>): ImposterPrompt[] =>
  rows.map(([word, category], index) => p(`${prefix}-${index + 11}`, word, category))

/** Family tier — 100 kid-safe words. */
export const impFamily: ContentPack<ImposterPrompt> = {
  id: 'imposter-family-v1',
  game: 'imposter',
  tone: 'family',
  locale: 'en',
  prompts: [
    p('imp-fam-1', 'Banana', 'Fruit'),
    p('imp-fam-2', 'Giraffe', 'Animal'),
    p('imp-fam-3', 'Pizza', 'Food'),
    p('imp-fam-4', 'Guitar', 'Instrument'),
    p('imp-fam-5', 'Beach', 'Place'),
    p('imp-fam-6', 'Rainbow', 'Nature'),
    p('imp-fam-7', 'Dentist', 'Job'),
    p('imp-fam-8', 'Soccer', 'Sport'),
    p('imp-fam-9', 'Pancake', 'Food'),
    p('imp-fam-10', 'Castle', 'Building'),
    ...more('imp-fam', [
      ['Elephant', 'Animal'],
      ['Lemon', 'Fruit'],
      ['Firetruck', 'Vehicle'],
      ['Moon', 'Space'],
      ['Violin', 'Instrument'],
      ['Playground', 'Place'],
      ['Cupcake', 'Food'],
      ['Penguin', 'Animal'],
      ['Bicycle', 'Vehicle'],
      ['Snowman', 'Winter'],
      ['Doctor', 'Job'],
      ['Basketball', 'Sport'],
      ['Waterfall', 'Nature'],
      ['Library', 'Place'],
      ['Strawberry', 'Fruit'],
      ['Dinosaur', 'Animal'],
      ['Rocket', 'Space'],
      ['Drum', 'Instrument'],
      ['Sandwich', 'Food'],
      ['Firefighter', 'Job'],
      ['Volleyball', 'Sport'],
      ['Treehouse', 'Building'],
      ['Butterfly', 'Insect'],
      ['Train', 'Vehicle'],
      ['Popcorn', 'Snack'],
      ['Mountain', 'Nature'],
      ['Telescope', 'Science'],
      ['Puppy', 'Animal'],
      ['School bus', 'Vehicle'],
      ['Ice cream', 'Dessert'],
      ['Astronaut', 'Job'],
      ['Baseball', 'Sport'],
      ['Igloo', 'Building'],
      ['Ladybug', 'Insect'],
      ['Airplane', 'Vehicle'],
      ['Watermelon', 'Fruit'],
      ['Ocean', 'Nature'],
      ['Piano', 'Instrument'],
      ['Zoo', 'Place'],
      ['Robot', 'Technology'],
      ['Turtle', 'Animal'],
      ['Cookie', 'Dessert'],
      ['Teacher', 'Job'],
      ['Swimming', 'Sport'],
      ['Lighthouse', 'Building'],
      ['Sunflower', 'Plant'],
      ['Helicopter', 'Vehicle'],
      ['Mango', 'Fruit'],
      ['River', 'Nature'],
      ['Trumpet', 'Instrument'],
      ['Museum', 'Place'],
      ['Kite', 'Toy'],
      ['Koala', 'Animal'],
      ['Spaghetti', 'Food'],
      ['Farmer', 'Job'],
      ['Tennis', 'Sport'],
      ['Skyscraper', 'Building'],
      ['Cactus', 'Plant'],
      ['Submarine', 'Vehicle'],
      ['Blueberry', 'Fruit'],
      ['Thunderstorm', 'Weather'],
      ['Flute', 'Instrument'],
      ['Aquarium', 'Place'],
      ['Yo-yo', 'Toy'],
      ['Zebra', 'Animal'],
      ['Taco', 'Food'],
      ['Pilot', 'Job'],
      ['Hockey', 'Sport'],
      ['Barn', 'Building'],
      ['Oak tree', 'Plant'],
      ['Scooter', 'Vehicle'],
      ['Pineapple', 'Fruit'],
      ['Volcano', 'Nature'],
      ['Saxophone', 'Instrument'],
      ['Amusement park', 'Place'],
      ['Puzzle', 'Toy'],
      ['Otter', 'Animal'],
      ['Pretzel', 'Snack'],
      ['Veterinarian', 'Job'],
      ['Gymnastics', 'Sport'],
      ['Windmill', 'Building'],
      ['Daisy', 'Plant'],
      ['Sailboat', 'Vehicle'],
      ['Peach', 'Fruit'],
      ['Cave', 'Nature'],
      ['Cello', 'Instrument'],
      ['Bakery', 'Place'],
      ['Teddy bear', 'Toy'],
      ['Hedgehog', 'Animal'],
      ['Waffle', 'Food'],
    ]),
  ],
}

/** Friends tier — 100 general-audience relatables. */
export const impFriends: ContentPack<ImposterPrompt> = {
  id: 'imposter-friends-v1',
  game: 'imposter',
  tone: 'friends',
  locale: 'en',
  prompts: [
    p('imp-fri-1', 'Karaoke', 'Activity'),
    p('imp-fri-2', 'Road trip', 'Activity'),
    p('imp-fri-3', 'Ghosting', 'Dating'),
    p('imp-fri-4', 'Brunch', 'Food'),
    p('imp-fri-5', 'Gym selfie', 'Social media'),
    p('imp-fri-6', 'Group project', 'School'),
    p('imp-fri-7', 'Wi-Fi password', 'Tech'),
    p('imp-fri-8', 'Monday', 'Time'),
    p('imp-fri-9', 'Escape room', 'Activity'),
    p('imp-fri-10', 'Airport security', 'Travel'),
    ...more('imp-fri', [
      ['Coffee run', 'Routine'],
      ['Video call', 'Tech'],
      ['Food truck', 'Food'],
      ['Concert ticket', 'Entertainment'],
      ['Flat tire', 'Travel'],
      ['Inside joke', 'Friendship'],
      ['Streaming password', 'Tech'],
      ['Happy hour', 'Night out'],
      ['Laundry day', 'Chore'],
      ['Board game night', 'Activity'],
      ['Takeout menu', 'Food'],
      ['Train delay', 'Travel'],
      ['Voice note', 'Messaging'],
      ['Spoiler alert', 'Entertainment'],
      ['Office kitchen', 'Work'],
      ['Camping trip', 'Travel'],
      ['Online shopping', 'Activity'],
      ['Trivia night', 'Night out'],
      ['Unread email', 'Work'],
      ['Phone charger', 'Tech'],
      ['Movie marathon', 'Entertainment'],
      ['Potluck', 'Food'],
      ['Parallel parking', 'Driving'],
      ['Alarm snooze', 'Routine'],
      ['Photo dump', 'Social media'],
      ['Weekend plans', 'Social'],
      ['Hotel breakfast', 'Travel'],
      ['Fantasy league', 'Sport'],
      ['Subscription trial', 'Shopping'],
      ['Work deadline', 'Work'],
      ['Coffee shop', 'Place'],
      ['Podcast', 'Entertainment'],
      ['Carry-on bag', 'Travel'],
      ['Awkward silence', 'Social'],
      ['Food delivery', 'Food'],
      ['Playlist shuffle', 'Music'],
      ['Fitness tracker', 'Tech'],
      ['Game night', 'Activity'],
      ['Email thread', 'Work'],
      ['Window seat', 'Travel'],
      ['Meme', 'Internet'],
      ['Dinner reservation', 'Night out'],
      ['Thrift store', 'Shopping'],
      ['Traffic jam', 'Travel'],
      ['Roommate', 'Home'],
      ['Password reset', 'Tech'],
      ['Open mic', 'Entertainment'],
      ['Leftovers', 'Food'],
      ['Weekend getaway', 'Travel'],
      ['Office party', 'Work'],
      ['Book club', 'Activity'],
      ['Muted microphone', 'Tech'],
      ['Food court', 'Place'],
      ['Rain check', 'Social'],
      ['Pub quiz', 'Night out'],
      ['Baggage claim', 'Travel'],
      ['Autocorrect', 'Tech'],
      ['Birthday group chat', 'Social'],
      ['Meal prep', 'Food'],
      ['Commute', 'Routine'],
      ['Photo booth', 'Entertainment'],
      ['Garage sale', 'Shopping'],
      ['Couch nap', 'Routine'],
      ['Late checkout', 'Travel'],
      ['Reaction GIF', 'Internet'],
      ['Team meeting', 'Work'],
      ['Shared calendar', 'Tech'],
      ['Tailgate', 'Social'],
      ['Midnight snack', 'Food'],
      ['Delayed flight', 'Travel'],
      ['Housewarming', 'Social'],
      ['Noise-canceling headphones', 'Tech'],
      ['Comedy show', 'Entertainment'],
      ['Grocery list', 'Chore'],
      ['Carpool', 'Travel'],
      ['Elevator small talk', 'Social'],
      ['Laptop update', 'Tech'],
      ['Farmers market', 'Shopping'],
      ['Dance floor', 'Night out'],
      ['Out-of-office reply', 'Work'],
      ['Recipe video', 'Food'],
      ['Vacation photo', 'Travel'],
      ['Quiz show', 'Entertainment'],
      ['Moving day', 'Chore'],
      ['Bluetooth speaker', 'Tech'],
      ['Picnic', 'Activity'],
      ['Delivery notification', 'Shopping'],
      ['Rush hour', 'Travel'],
      ['Community theater', 'Entertainment'],
      ['Shared apartment', 'Home'],
    ]),
  ],
}

/** Spicy tier — 100 adult prompts; host confirms the age gate before starting. */
export const impSpicy: ContentPack<ImposterPrompt> = {
  id: 'imposter-spicy-v1',
  game: 'imposter',
  tone: 'spicy',
  locale: 'en',
  prompts: [
    p('imp-spi-1', 'First date', 'Dating'),
    p('imp-spi-2', 'Situationship', 'Dating'),
    p('imp-spi-3', 'Walk of shame', 'Night out'),
    p('imp-spi-4', 'Love bite', 'Romance'),
    p('imp-spi-5', 'Skinny dip', 'Activity'),
    p('imp-spi-6', "Ex's playlist", 'Music'),
    p('imp-spi-7', 'Dating app bio', 'Tech'),
    p('imp-spi-8', 'One-night stand', 'Dating'),
    p('imp-spi-9', 'Body shot', 'Party'),
    p('imp-spi-10', 'Friends with benefits', 'Dating'),
    ...more('imp-spi', [
      ['Blind date', 'Dating'],
      ['Flirty text', 'Messaging'],
      ['Cocktail bar', 'Night out'],
      ['Anniversary dinner', 'Romance'],
      ['Secret crush', 'Romance'],
      ['Wingperson', 'Dating'],
      ['Last call', 'Night out'],
      ['Love letter', 'Romance'],
      ['Matching tattoo', 'Relationship'],
      ['Champagne toast', 'Celebration'],
      ['Pickup line', 'Dating'],
      ['Slow dance', 'Romance'],
      ['Rooftop bar', 'Night out'],
      ['Double date', 'Dating'],
      ['Morning-after text', 'Messaging'],
      ['Candlelit dinner', 'Romance'],
      ['Bachelor party', 'Celebration'],
      ['Bachelorette party', 'Celebration'],
      ['Flirtini', 'Cocktail'],
      ['Ex encounter', 'Dating'],
      ['Hotel bar', 'Night out'],
      ['Love song dedication', 'Music'],
      ['Dating app match', 'Tech'],
      ['Couples costume', 'Relationship'],
      ['Late-night call', 'Messaging'],
      ['Romantic getaway', 'Travel'],
      ['Dance partner', 'Night out'],
      ['Engagement ring', 'Romance'],
      ['Kiss cam', 'Entertainment'],
      ['Secret admirer', 'Romance'],
      ['Cocktail dress', 'Fashion'],
      ['Rebound date', 'Dating'],
      ['Balcony kiss', 'Romance'],
      ['Singles mixer', 'Night out'],
      ['Flirty emoji', 'Messaging'],
      ['Honeymoon suite', 'Travel'],
      ['Speed dating', 'Dating'],
      ['Love triangle', 'Relationship'],
      ['Midnight toast', 'Celebration'],
      ['Boudoir photo', 'Photography'],
      ['Rom-com marathon', 'Entertainment'],
      ['Dinner date', 'Dating'],
      ['Couples massage', 'Wellness'],
      ['Nightclub queue', 'Night out'],
      ['Perfume sample', 'Beauty'],
      ['First kiss', 'Romance'],
      ['Dating profile photo', 'Tech'],
      ['Velvet rope', 'Night out'],
      ['Weekend fling', 'Dating'],
      ['Romantic comedy', 'Entertainment'],
      ['Couples nickname', 'Relationship'],
      ['Martini', 'Cocktail'],
      ['Ex reunion', 'Dating'],
      ['Love poem', 'Romance'],
      ['Dance club', 'Night out'],
      ['Floral bouquet', 'Romance'],
      ['Flirty banter', 'Dating'],
      ['After-party', 'Night out'],
      ['Couples selfie', 'Social media'],
      ['Satin robe', 'Fashion'],
      ['Vacation romance', 'Dating'],
      ['Wedding date', 'Dating'],
      ['Makeup mirror', 'Beauty'],
      ['Crush confession', 'Romance'],
      ['Cocktail napkin number', 'Dating'],
      ['Moonlit walk', 'Romance'],
      ['Singles cruise', 'Travel'],
      ['Matching pajamas', 'Relationship'],
      ['Date-night cologne', 'Beauty'],
      ['Proposal speech', 'Romance'],
      ['VIP booth', 'Night out'],
      ['Love horoscope', 'Entertainment'],
      ['Flirty compliment', 'Dating'],
      ['Heart-shaped box', 'Gift'],
      ['Wedding dance', 'Celebration'],
      ['Couples playlist', 'Music'],
      ['Secret rendezvous', 'Dating'],
      ['Night-out heels', 'Fashion'],
      ['Romantic picnic', 'Romance'],
      ['Dating app notification', 'Tech'],
      ['Champagne bucket', 'Night out'],
      ['Love at first sight', 'Romance'],
      ['Ex voicemail', 'Messaging'],
      ['Couples vacation', 'Travel'],
      ['Red lipstick', 'Beauty'],
      ['Late-night diner', 'Night out'],
      ['Romantic surprise', 'Romance'],
      ['Date-night outfit', 'Fashion'],
      ['Flirty wink', 'Dating'],
      ['Wedding bouquet toss', 'Celebration'],
    ]),
  ],
}
