import type { ContentPack, MltPrompt } from '@hpg/shared'

const p = (id: string, text: string): MltPrompt => ({ id, text })

/** Family tier — kid-safe. 100 prompts. */
export const mltFamily: ContentPack<MltPrompt> = {
  id: 'mlt-family-v1',
  game: 'most-likely-to',
  tone: 'family',
  locale: 'en',
  prompts: [
    p('mlt-fam-1', 'become a famous inventor'),
    p('mlt-fam-2', 'forget their own birthday'),
    p('mlt-fam-3', 'laugh at the worst possible moment'),
    p('mlt-fam-4', 'win a gold medal someday'),
    p('mlt-fam-5', 'eat dessert before dinner'),
    p('mlt-fam-6', 'get lost inside a mall'),
    p('mlt-fam-7', 'adopt ten pets'),
    p('mlt-fam-8', 'sleep through three alarms'),
    p('mlt-fam-9', 'become a teacher'),
    p('mlt-fam-10', 'talk to animals like they understand'),
    ...mlt('fam', 11, [
      'build the tallest blanket fort',
      'name every cloud they see',
      'win a school talent show',
      'invent a brand-new holiday',
      'pack too many snacks for a trip',
      'read every book in a library',
      'make friends with a shy animal',
      'wear mismatched socks on purpose',
      'discover a hidden treasure',
      'tell the funniest bedtime story',
      'grow the biggest pumpkin',
      'be ready before everyone else',
      'turn a cardboard box into a spaceship',
      'sing while doing chores',
      'start a neighborhood parade',
      'remember every tiny detail',
      'draw a comic book',
      'build a robot helper',
      'share the last cookie',
      'ask the most questions at a museum',
      'win a staring contest',
      'make a rainy day fun',
      'spot a shooting star first',
      'learn a magic trick overnight',
      'organize the best scavenger hunt',
      'befriend a new student first',
      'create a secret handshake',
      'bring home an unusual souvenir',
      'know every answer at trivia night',
      'dance when nobody else is dancing',
      'build an amazing sandcastle',
      'get excited about a science experiment',
      'save every interesting rock',
      'wear a costume on an ordinary day',
      'turn dinner into a picnic',
      'finish a giant puzzle first',
      'write a story about a dragon',
      'make everyone laugh during a long trip',
      'choose breakfast for dinner',
      'become an astronaut',
      'teach a pet a clever trick',
      'find the best hiding place',
      'make a gift by hand',
      'start a collection of something unusual',
      'win a spelling bee',
      'plant a garden for butterflies',
      'build a snow creature instead of a snowman',
      'bring extra supplies for everyone',
      'wake up early for an adventure',
      'turn a mistake into a great idea',
      'create a new playground game',
      'learn every constellation',
      'decorate for a holiday months early',
      'carry a book everywhere',
      'make up a song about lunch',
      'volunteer to go first',
      'notice someone needs cheering up',
      'design a treehouse',
      'solve a riddle before anyone else',
      'wear a hat indoors all day',
      'save a snack for later',
      'make the perfect paper airplane',
      'lead a nature walk',
      'give every stuffed animal a name',
      'build something useful from blocks',
      'turn cleanup into a race',
      'try the strangest ice-cream flavor',
      'write a letter to their future self',
      'make a map of an imaginary world',
      'spot an animal hiding nearby',
      'create the loudest cheering section',
      'choose the messiest craft project',
      'learn to juggle',
      'make friends while waiting in line',
      'find a creative shortcut',
      'bring an umbrella on a sunny day',
      'start laughing and make everyone join in',
      'become a park ranger',
      'make a museum exhibit at home',
      'choose the longest waterslide',
      'build a miniature city',
      'tell a joke to break the silence',
      'pack for every possible kind of weather',
      'turn leaves into artwork',
      'offer to help without being asked',
      'create an award for everyone',
      'find shapes in the stars',
      'make the coziest reading corner',
      'lead a singalong',
      'turn waiting in line into a game',
    ]),
  ],
}

/** Friends tier — general audience, mildly cheeky. 100 prompts. */
export const mltFriends: ContentPack<MltPrompt> = {
  id: 'mlt-friends-v1',
  game: 'most-likely-to',
  tone: 'friends',
  locale: 'en',
  prompts: [
    p('mlt-fri-1', 'become famous accidentally'),
    p('mlt-fri-2', 'send a message to the wrong group chat'),
    p('mlt-fri-3', 'ghost the group chat for a week'),
    p('mlt-fri-4', 'cry at a commercial'),
    p('mlt-fri-5', 'buy concert tickets before checking the calendar'),
    p('mlt-fri-6', 'forget where they parked'),
    p('mlt-fri-7', 'trip over absolutely nothing'),
    p('mlt-fri-8', 'argue with a stranger online'),
    p('mlt-fri-9', 'get a tattoo on a whim'),
    p('mlt-fri-10', 'become a millionaire and lose it all'),
    ...mlt('fri', 11, [
      'arrive with snacks for everyone',
      'plan a trip down to the minute',
      'miss a flight while at the airport',
      'start a group chat for a minor event',
      'remember a face but forget the name',
      'order the same meal every time',
      'turn a quick story into a long saga',
      'find the best hidden restaurant',
      'volunteer to host game night',
      'bring a suitcase for a weekend away',
      'make friends in an elevator',
      'send a voice note longer than a podcast',
      'laugh before reaching the punchline',
      'have twenty unread notifications',
      'know a shortcut that takes longer',
      'suggest dessert before ordering dinner',
      'create the perfect road-trip playlist',
      'fall asleep during a movie they chose',
      'be early to a casual hangout',
      'turn a hobby into a side business',
      'take the best candid photo',
      'keep every souvenir ticket',
      'recommend a show nobody else has seen',
      'wear sunglasses on a cloudy day',
      'win a trivia night on a lucky guess',
      'start packing a week early',
      'forget why they entered a room',
      'organize a themed dinner',
      'befriend the host’s pet first',
      'know the words to every throwback song',
      'choose the longest possible route',
      'bring a board game to every gathering',
      'ask for a bite of everyone’s food',
      'make a color-coded spreadsheet for fun',
      'change outfits three times before leaving',
      'find a bargain nobody else noticed',
      'become a regular at a café',
      'reply instantly at an unusual hour',
      'leave a party without saying goodbye',
      'make an ordinary Tuesday feel special',
      'take charge during a travel delay',
      'send the perfect reaction image',
      'order the most adventurous item on the menu',
      'start dancing when a favorite song plays',
      'tell a stranger their life story',
      'book a spontaneous weekend trip',
      'bring home too many vacation photos',
      'win over a difficult crowd',
      'try a bizarre food combination',
      'have a strong opinion about fonts',
      'turn up with an unexpected plus-one',
      'make a five-minute task take an hour',
      'finish everyone else’s leftovers',
      'spot a celebrity first',
      'create a nickname that sticks',
      'keep a plant alive for decades',
      'start a friendly debate over nothing',
      'keep a perfectly organized calendar',
      'carry everything anyone might need',
      'take notes during a casual conversation',
      'find humor in an awkward silence',
      'order something impossible to pronounce',
      'be the last person still dancing',
      'quote a movie at exactly the right moment',
      'start planning the next gathering immediately',
      'bring homemade food to a party',
      'have a perfectly organized camera roll',
      'lose track of time in a bookstore',
      'lead a singalong during a long delay',
      'know exactly when to leave a party',
      'wear the boldest outfit in the room',
      'suggest karaoke after dinner',
      'turn a minor inconvenience into a funny story',
      'save hundreds of browser tabs',
      'choose the dessert everyone wants',
      'give surprisingly practical advice',
      'laugh during a serious photo',
      'find the quietest corner at a party',
      'convince everyone to stay out later',
      'bring a backup plan for the backup plan',
      'make breakfast at midnight',
      'discover a song before it becomes popular',
      'choose a window seat every time',
      'start a tradition by accident',
      'take the scenic route intentionally',
      'make a friend while traveling alone',
      'remember the Wi-Fi password',
      'suggest splitting one more appetizer',
      'spot a fake laugh immediately',
      'convince everyone to try a themed party',
    ]),
  ],
}

/** Spicy tier — 18+ only; host confirms the age gate before starting. 100 prompts. */
export const mltSpicy: ContentPack<MltPrompt> = {
  id: 'mlt-spicy-v1',
  game: 'most-likely-to',
  tone: 'spicy',
  locale: 'en',
  prompts: [
    p('mlt-spi-1', 'text an ex at 2am'),
    p('mlt-spi-2', 'use a hilariously outdated profile photo'),
    p('mlt-spi-3', 'kiss a stranger on vacation'),
    p('mlt-spi-4', 'accidentally date two people at once'),
    p('mlt-spi-5', 'flirt their way out of a parking ticket'),
    p('mlt-spi-6', 'marry someone they met a month ago'),
    p('mlt-spi-7', 'flirt confidently until someone flirts back'),
    p('mlt-spi-8', "slide into a celebrity's DMs"),
    p('mlt-spi-9', "get caught checking out their ex's profile"),
    p('mlt-spi-10', 'leave a bad date through the bathroom window'),
    ...mlt('spi', 11, [
      'send a work email with a vacation auto-reply still on',
      'wear an event wristband days after the event',
      'volunteer to give a toast and then go blank',
      'wave at a stranger who was waving at someone else',
      'bring a board game with key pieces missing',
      'get stuck chatting with the venue staff all night',
      'try the wrong hotel-room door after a late night',
      'blush after being singled out during a toast',
      'remember every detail from a first date',
      'ask friends to review a dating profile',
      'laugh through an awkward date',
      'spill a drink while trying to look charming',
      'have an unforgettable meet-cute',
      'overthink a one-word reply',
      'date someone with the opposite personality',
      'use an unbelievably cheesy pickup line',
      'plan an outfit days before a date',
      'react to a years-old post by accident',
      'turn friendship into a romance',
      'make the first move on the dance floor',
      'save every party wristband',
      'get caught staring at a crush',
      'send a screenshot to the person in it',
      'flirt without realizing it',
      'choose a date for the dessert menu',
      'write an excellent dating profile bio',
      'forget what they planned to say to a crush',
      'have friends arrange a blind date',
      'date someone they met while traveling',
      'mistake teasing for serious flirting',
      'rehearse an introduction in the mirror',
      'read too much into an emoji',
      'mistake a couples discount for a proposal hint',
      'end up in a long-distance romance',
      'show up in the same outfit as their date',
      'ask someone out with a handwritten note',
      'tell a date an embarrassing story too early',
      'notice chemistry before anyone else',
      'fall for the quiet person in the room',
      'share a playlist as a romantic gesture',
      'make a simple toast sound unintentionally dramatic',
      'receive a secret admirer note',
      'go on a date mainly for the story',
      'wave goodbye and then walk the same direction as their date',
      'have a signature flirting move',
      'turn a casual coffee into an all-day date',
      'choose karaoke for a first date',
      'be introduced to someone by relatives',
      'get teased about an obvious crush',
      'send the first message after a date',
      'keep a lucky first-date outfit',
      'date a morning person despite being a night owl',
      'make someone blush with one compliment',
      'become speechless around a crush',
      'send a flirty message with a spectacular typo',
      'choose chemistry over a perfect checklist',
      'have a romance worthy of a comedy',
      'ask for dating advice from the whole group',
      'mistake a date’s roommate for their date',
      'pretend to understand a crush’s unusual hobby',
      'plan a dramatic romantic reveal',
      'get distracted by a charming smile',
      'make friends with an ex eventually',
      'find love at a friend’s wedding',
      'turn down a perfect match at first',
      'use humor to recover from rejection',
      'have a date become a funny group story',
      'interrupt a romantic moment with a terrible joke',
      'change travel plans for a promising romance',
      'accidentally send a good-morning text to the wrong person',
      'share a pet name too early',
      'pick the perfect first-date location',
      'offer a breath mint and spill the entire pack on the table',
      'prefer slow-burn romance to instant sparks',
      'get flustered by direct eye contact',
      'save a draft message and accidentally send the worst version',
      'arrive at the right restaurant on the wrong night',
      'match with someone they already know',
      'date someone who challenges them at trivia',
      'turn an awkward introduction into chemistry',
      'laugh during the quietest moment of a fancy date',
      'confess feelings at the last possible moment',
      'misread the dress code and arrive wildly overdressed',
      'send a message with too many emojis',
      'forget the punchline while telling a joke at happy hour',
      'give bold dating advice they would never follow',
      'make a terrible first impression and recover',
      'plan a date around a shared obsession',
      'be remembered for confident flirting',
      'tell the best story about a bad date',
    ]),
  ],
}

function mlt(tone: 'fam' | 'fri' | 'spi', start: number, texts: string[]): MltPrompt[] {
  return texts.map((text, index) => p(`mlt-${tone}-${start + index}`, text))
}
