import type { ContentPack, NhiePrompt } from '@hpg/shared'

const p = (id: string, text: string): NhiePrompt => ({ id, text })

/** Family tier — 100 kid-safe statements that complete "Never have I ever …". */
export const nhieFamily: ContentPack<NhiePrompt> = {
  id: 'nhie-family-v1',
  game: 'never-have-i-ever',
  tone: 'family',
  locale: 'en',
  prompts: [
    p('nhie-fam-1', 'broken a bone'),
    p('nhie-fam-2', 'stayed up all night'),
    p('nhie-fam-3', 'eaten food off the floor'),
    p('nhie-fam-4', "forgotten someone's name mid-conversation"),
    p('nhie-fam-5', 'sung in the shower'),
    p('nhie-fam-6', 'lost a library book'),
    p('nhie-fam-7', 'talked to myself out loud'),
    p('nhie-fam-8', 'pretended to be asleep'),
    p('nhie-fam-9', 'been on TV'),
    p('nhie-fam-10', 'had a secret handshake'),
    p('nhie-fam-11', 'built a blanket fort'),
    p('nhie-fam-12', 'worn mismatched socks on purpose'),
    p('nhie-fam-13', 'named a stuffed animal'),
    p('nhie-fam-14', 'made breakfast for someone else'),
    p('nhie-fam-15', 'caught a snowflake on my tongue'),
    p('nhie-fam-16', 'won a board game'),
    p('nhie-fam-17', 'drawn on a foggy window'),
    p('nhie-fam-18', 'made up a dance'),
    p('nhie-fam-19', 'kept a lucky object'),
    p('nhie-fam-20', 'laughed during a quiet moment'),
    p('nhie-fam-21', 'worn pajamas all day'),
    p('nhie-fam-22', 'made a paper airplane'),
    p('nhie-fam-23', 'helped bake a cake'),
    p('nhie-fam-24', 'read a whole book in one day'),
    p('nhie-fam-25', 'invented a new game'),
    p('nhie-fam-26', 'slept in a tent'),
    p('nhie-fam-27', 'collected rocks or shells'),
    p('nhie-fam-28', 'made a friendship bracelet'),
    p('nhie-fam-29', 'forgotten where I put my shoes'),
    p('nhie-fam-30', 'given a pet a silly nickname'),
    p('nhie-fam-31', 'tried to lick my elbow'),
    p('nhie-fam-32', 'played in the rain'),
    p('nhie-fam-33', 'eaten dessert before dinner'),
    p('nhie-fam-34', 'made a wish on a star'),
    p('nhie-fam-35', 'had a lemonade stand'),
    p('nhie-fam-36', 'worn a costume when it was not Halloween'),
    p('nhie-fam-37', 'built something out of cardboard'),
    p('nhie-fam-38', 'learned a magic trick'),
    p('nhie-fam-39', 'made an animal shape from clouds'),
    p('nhie-fam-40', 'gotten the hiccups from laughing'),
    p('nhie-fam-41', 'eaten cereal for dinner'),
    p('nhie-fam-42', 'written a story for fun'),
    p('nhie-fam-43', 'given someone a handmade gift'),
    p('nhie-fam-44', 'tried a food because of its funny name'),
    p('nhie-fam-45', 'built a sandcastle'),
    p('nhie-fam-46', 'ridden a carousel'),
    p('nhie-fam-47', 'memorized a tongue twister'),
    p('nhie-fam-48', 'made a face at myself in a mirror'),
    p('nhie-fam-49', 'had a picnic indoors'),
    p('nhie-fam-50', 'watched the sunrise'),
    p('nhie-fam-51', 'made my own bookmark'),
    p('nhie-fam-52', 'worn a hat that was too big'),
    p('nhie-fam-53', 'jumped in a pile of leaves'),
    p('nhie-fam-54', 'taught someone how to play a game'),
    p('nhie-fam-55', 'made shadow puppets'),
    p('nhie-fam-56', 'spotted a rainbow'),
    p('nhie-fam-57', 'packed my own lunch'),
    p('nhie-fam-58', 'grown a plant from a seed'),
    p('nhie-fam-59', 'made a card for no special occasion'),
    p('nhie-fam-60', 'whistled a whole tune'),
    p('nhie-fam-61', 'worn my shirt backward by accident'),
    p('nhie-fam-62', 'made a snack shaped like a face'),
    p('nhie-fam-63', 'played hide-and-seek'),
    p('nhie-fam-64', 'read under the covers with a flashlight'),
    p('nhie-fam-65', 'pretended the floor was lava'),
    p('nhie-fam-66', 'made a snow angel'),
    p('nhie-fam-67', 'sent a postcard'),
    p('nhie-fam-68', 'finished a jigsaw puzzle'),
    p('nhie-fam-69', 'balanced a spoon on my nose'),
    p('nhie-fam-70', 'made up a silly word'),
    p('nhie-fam-71', 'visited a farm'),
    p('nhie-fam-72', 'tried to count all the stars'),
    p('nhie-fam-73', 'decorated a cookie'),
    p('nhie-fam-74', 'performed in a school show'),
    p('nhie-fam-75', 'found a four-leaf clover'),
    p('nhie-fam-76', 'made a time capsule'),
    p('nhie-fam-77', 'had a bedroom dance party'),
    p('nhie-fam-78', 'used a banana as a pretend phone'),
    p('nhie-fam-79', 'made a bird feeder'),
    p('nhie-fam-80', 'fallen asleep during a car ride'),
    p('nhie-fam-81', 'written with sidewalk chalk'),
    p('nhie-fam-82', 'helped wash a car'),
    p('nhie-fam-83', 'made a sculpture from clay'),
    p('nhie-fam-84', 'caught a firefly'),
    p('nhie-fam-85', 'worn slippers outside'),
    p('nhie-fam-86', 'told a joke that made everyone groan'),
    p('nhie-fam-87', 'made a chain from paper loops'),
    p('nhie-fam-88', 'found money in a coat pocket'),
    p('nhie-fam-89', 'skipped stones across water'),
    p('nhie-fam-90', 'made a puppet from a sock'),
    p('nhie-fam-91', 'eaten a fruit straight from a garden'),
    p('nhie-fam-92', 'built a tower taller than me'),
    p('nhie-fam-93', 'had a race with a sibling or friend'),
    p('nhie-fam-94', 'made homemade bubbles'),
    p('nhie-fam-95', 'learned a word in another language'),
    p('nhie-fam-96', 'watched ants carry food'),
    p('nhie-fam-97', 'made a crown from paper'),
    p('nhie-fam-98', 'shared my favorite snack'),
    p('nhie-fam-99', 'given a name to a plant'),
    p('nhie-fam-100', 'made someone laugh with a funny voice'),
  ],
}

/** Friends tier — 100 general-audience, mildly cheeky statements. */
export const nhieFriends: ContentPack<NhiePrompt> = {
  id: 'nhie-friends-v1',
  game: 'never-have-i-ever',
  tone: 'friends',
  locale: 'en',
  prompts: [
    p('nhie-fri-1', 'missed a flight'),
    p('nhie-fri-2', 'fallen asleep at the movies'),
    p('nhie-fri-3', 'texted the wrong person'),
    p('nhie-fri-4', 'pretended to know a song'),
    p('nhie-fri-5', 'googled myself'),
    p('nhie-fri-6', 'laughed till I cried in public'),
    p('nhie-fri-7', "forgotten a friend's birthday"),
    p('nhie-fri-8', 'lied about my age'),
    p('nhie-fri-9', 'walked into a glass door'),
    p('nhie-fri-10', 'returned a gift for the money'),
    p('nhie-fri-11', 'sent a message to the group chat about the group chat'),
    p('nhie-fri-12', 'rehearsed an argument in the shower'),
    p('nhie-fri-13', 'ordered the same meal three times in one week'),
    p('nhie-fri-14', 'pretended my camera was broken on a video call'),
    p('nhie-fri-15', 'waved back at someone who was not waving at me'),
    p('nhie-fri-16', 'left a party without saying goodbye'),
    p('nhie-fri-17', 'watched an entire season in one day'),
    p('nhie-fri-18', 'used a fake excuse to cancel plans'),
    p('nhie-fri-19', 'forgotten why I walked into a room'),
    p('nhie-fri-20', 'snoozed an alarm more than five times'),
    p('nhie-fri-21', 'taken a photo of my food'),
    p('nhie-fri-22', 'cried over a fictional character'),
    p('nhie-fri-23', 'made a playlist for a very specific mood'),
    p('nhie-fri-24', 'worn sunglasses indoors'),
    p('nhie-fri-25', 'claimed I was five minutes away when I had not left'),
    p('nhie-fri-26', 'sung the wrong lyrics with confidence'),
    p('nhie-fri-27', 'bought something because an influencer recommended it'),
    p('nhie-fri-28', 'laughed at a joke I did not understand'),
    p('nhie-fri-29', 'checked the fridge twice hoping something new appeared'),
    p('nhie-fri-30', 'started a hobby and abandoned it within a week'),
    p('nhie-fri-31', 'muted a group chat for more than a month'),
    p('nhie-fri-32', 'dressed up only to have my plans canceled'),
    p('nhie-fri-33', 'used the last of something and put the empty package back'),
    p('nhie-fri-34', 'made a purchase after midnight'),
    p('nhie-fri-35', 'taken more than twenty photos to get one good picture'),
    p('nhie-fri-36', 'forgotten a password immediately after changing it'),
    p('nhie-fri-37', 'pretended not to see someone in public'),
    p('nhie-fri-38', 'gone to an event on the wrong day'),
    p('nhie-fri-39', 'used a meme instead of answering a question'),
    p('nhie-fri-40', 'finished someone else’s fries'),
    p('nhie-fri-41', 'replayed a voice message before sending it'),
    p('nhie-fri-42', 'gotten lost while following directions'),
    p('nhie-fri-43', 'pretended to be busy to avoid small talk'),
    p('nhie-fri-44', 'brought home a souvenir I never used'),
    p('nhie-fri-45', 'put an outfit back on because nobody saw it'),
    p('nhie-fri-46', 'eaten a snack meant for sharing by myself'),
    p('nhie-fri-47', 'looked up the ending before finishing a show'),
    p('nhie-fri-48', 'made plans while hoping they would be canceled'),
    p('nhie-fri-49', 'replied to an email only in my head'),
    p('nhie-fri-50', 'missed my stop because I was distracted'),
    p('nhie-fri-51', 'kept a cardboard box because it was a good box'),
    p('nhie-fri-52', 'judged a restaurant by its menu font'),
    p('nhie-fri-53', 'worn headphones with nothing playing'),
    p('nhie-fri-54', 'taken a personality quiz seriously'),
    p('nhie-fri-55', 'forgotten to unmute before talking'),
    p('nhie-fri-56', 'celebrated when plans got canceled'),
    p('nhie-fri-57', 'made a dramatic exit and then returned for something'),
    p('nhie-fri-58', 'used an old photo as if it were recent'),
    p('nhie-fri-59', 'searched for my phone while holding it'),
    p('nhie-fri-60', 'accepted terms and conditions without reading them'),
    p('nhie-fri-61', 'had coffee after saying I was cutting back'),
    p('nhie-fri-62', 'let laundry sit unfolded for several days'),
    p('nhie-fri-63', 'made up a backstory for a stranger'),
    p('nhie-fri-64', 'saved a recipe I never cooked'),
    p('nhie-fri-65', 'joined a meeting from bed'),
    p('nhie-fri-66', 'pretended a typo was intentional'),
    p('nhie-fri-67', 'ordered food while groceries were at home'),
    p('nhie-fri-68', 'forgotten the plot of a movie while watching it'),
    p('nhie-fri-69', 'made a to-do list just to add a completed task'),
    p('nhie-fri-70', 'kept a tab open for more than a month'),
    p('nhie-fri-71', 'borrowed a book and kept it for years'),
    p('nhie-fri-72', 'used a filter and forgotten it was on'),
    p('nhie-fri-73', 'said “you too” at the wrong time'),
    p('nhie-fri-74', 'gone out solely because I liked my outfit'),
    p('nhie-fri-75', 'searched my symptoms online and regretted it'),
    p('nhie-fri-76', 'put off a two-minute task all day'),
    p('nhie-fri-77', 'listened to one song on repeat for hours'),
    p('nhie-fri-78', 'left a shopping cart because the checkout line was long'),
    p('nhie-fri-79', 'used a friend as an excuse without telling them'),
    p('nhie-fri-80', 'practiced pronouncing a name before saying it'),
    p('nhie-fri-81', 'accidentally liked an old social media post'),
    p('nhie-fri-82', 'chosen a restaurant based on the dessert menu'),
    p('nhie-fri-83', 'pretended to remember someone I had forgotten'),
    p('nhie-fri-84', 'set an alarm to remember another alarm'),
    p('nhie-fri-85', 'used a chair as a clothes rack'),
    p('nhie-fri-86', 'read a message preview and avoided opening it'),
    p('nhie-fri-87', 'taken a nap that lasted until the next meal'),
    p('nhie-fri-88', 'packed too much for a weekend trip'),
    p('nhie-fri-89', 'laughed at my own joke before finishing it'),
    p('nhie-fri-90', 'created a folder and still lost the file'),
    p('nhie-fri-91', 'bought matching items with a friend'),
    p('nhie-fri-92', 'watched a tutorial at double speed'),
    p('nhie-fri-93', 'started cleaning to avoid another task'),
    p('nhie-fri-94', 'made an excuse to leave an awkward conversation'),
    p('nhie-fri-95', 'used a coupon and felt unusually proud'),
    p('nhie-fri-96', 'gone to the store and forgotten the one thing I needed'),
    p('nhie-fri-97', 'sent a screenshot back to the person in it'),
    p('nhie-fri-98', 'changed seats to get closer to an outlet'),
    p('nhie-fri-99', 'planned a vacation I never booked'),
    p('nhie-fri-100', 'given a stranger a nickname in my head'),
  ],
}

/** Spicy tier — 100 adult prompts; host confirms the age gate before starting. */
export const nhieSpicy: ContentPack<NhiePrompt> = {
  id: 'nhie-spicy-v1',
  game: 'never-have-i-ever',
  tone: 'spicy',
  locale: 'en',
  prompts: [
    p('nhie-spi-1', "kissed someone whose name I didn't know"),
    p('nhie-spi-2', 'dated two people in the same week'),
    p('nhie-spi-3', "checked a partner's phone"),
    p('nhie-spi-4', 'ghosted someone'),
    p('nhie-spi-5', 'been kicked out of a bar'),
    p('nhie-spi-6', 'gone skinny dipping'),
    p('nhie-spi-7', 'lied on a dating profile'),
    p('nhie-spi-8', 'had a crush on a coworker'),
    p('nhie-spi-9', 'sent a risky text and instantly regretted it'),
    p('nhie-spi-10', 'pretended to be single'),
    p('nhie-spi-11', 'flirted to get a free drink'),
    p('nhie-spi-12', 'matched with someone I already knew'),
    p('nhie-spi-13', 'used a friend to escape a bad date'),
    p('nhie-spi-14', 'sent the first message on a dating app'),
    p('nhie-spi-15', 'kissed someone on the first date'),
    p('nhie-spi-16', 'had a crush on a friend’s sibling'),
    p('nhie-spi-17', 'gone on a date mainly for the restaurant'),
    p('nhie-spi-18', 'rehearsed a flirty text with friends'),
    p('nhie-spi-19', 'pretended not to notice someone flirting with me'),
    p('nhie-spi-20', 'had a date end before the appetizers arrived'),
    p('nhie-spi-21', 'looked up a date before meeting them'),
    p('nhie-spi-22', 'flirted with someone in a checkout line'),
    p('nhie-spi-23', 'used a cheesy pickup line seriously'),
    p('nhie-spi-24', 'worn an outfit chosen to impress one person'),
    p('nhie-spi-25', 'developed a crush during a vacation'),
    p('nhie-spi-26', 'agreed to a second date and changed my mind'),
    p('nhie-spi-27', 'danced on a table'),
    p('nhie-spi-28', 'sent a flirty message to the wrong chat'),
    p('nhie-spi-29', 'had a friend write my dating profile'),
    p('nhie-spi-30', 'kept talking to someone because their pet was cute'),
    p('nhie-spi-31', 'made eye contact across a crowded room'),
    p('nhie-spi-32', 'had a crush on a bartender'),
    p('nhie-spi-33', 'used a fake name at a bar'),
    p('nhie-spi-34', 'planned a date around a perfect photo spot'),
    p('nhie-spi-35', 'been set up on a blind date'),
    p('nhie-spi-36', 'flirted through a shared playlist'),
    p('nhie-spi-37', 'deleted and reinstalled a dating app in one day'),
    p('nhie-spi-38', 'kissed someone at midnight on New Year’s Eve'),
    p('nhie-spi-39', 'had a date forget my name'),
    p('nhie-spi-40', 'pretended to like a hobby to impress a crush'),
    p('nhie-spi-41', 'had a crush on my roommate'),
    p('nhie-spi-42', 'gone to a singles event'),
    p('nhie-spi-43', 'asked a stranger for their number'),
    p('nhie-spi-44', 'had someone use my own pickup line on me'),
    p('nhie-spi-45', 'changed my plans after getting a flirty invitation'),
    p('nhie-spi-46', 'been recognized from a dating profile'),
    p('nhie-spi-47', 'had a date show up in a matching outfit'),
    p('nhie-spi-48', 'kissed a friend and then acted normal'),
    p('nhie-spi-49', 'sent a selfie and waited nervously for a reply'),
    p('nhie-spi-50', 'made a playlist for a crush'),
    p('nhie-spi-51', 'had a date turn into an all-night conversation'),
    p('nhie-spi-52', 'flirted with someone using only emojis'),
    p('nhie-spi-53', 'gone dancing just to see one person'),
    p('nhie-spi-54', 'had a crush on someone completely wrong for me'),
    p('nhie-spi-55', 'asked friends to analyze a one-word reply'),
    p('nhie-spi-56', 'arrived early to a date and pretended I had not'),
    p('nhie-spi-57', 'kept a souvenir from a memorable date'),
    p('nhie-spi-58', 'invented a signal for friends to rescue me'),
    p('nhie-spi-59', 'gone home with someone else’s jacket'),
    p('nhie-spi-60', 'flirted with a rival during a game'),
    p('nhie-spi-61', 'had two friends interested in the same person as me'),
    p('nhie-spi-62', 'made a grand romantic gesture'),
    p('nhie-spi-63', 'received flowers from a secret admirer'),
    p('nhie-spi-64', 'gone to karaoke to impress a date'),
    p('nhie-spi-65', 'matched with a friend’s ex'),
    p('nhie-spi-66', 'flirted with someone while wearing a ridiculous costume'),
    p('nhie-spi-67', 'left my number on a receipt'),
    p('nhie-spi-68', 'had a date interrupted by an ex'),
    p('nhie-spi-69', 'tried speed dating'),
    p('nhie-spi-70', 'taken advice from a dating horoscope'),
    p('nhie-spi-71', 'been serenaded in public'),
    p('nhie-spi-72', 'had a crush on a neighbor'),
    p('nhie-spi-73', 'sent a flirty voice note and replayed it repeatedly'),
    p('nhie-spi-74', 'gone on a date during a work trip'),
    p('nhie-spi-75', 'mistaken friendliness for flirting'),
    p('nhie-spi-76', 'dressed up for a video date'),
    p('nhie-spi-77', 'had a date planned entirely by friends'),
    p('nhie-spi-78', 'given someone my number on a dare'),
    p('nhie-spi-79', 'flirted with someone over a board game'),
    p('nhie-spi-80', 'gone on a date with someone who shared my name'),
    p('nhie-spi-81', 'received a love note with no signature'),
    p('nhie-spi-82', 'pretended to be mysterious on a date'),
    p('nhie-spi-83', 'had a friend accidentally reveal my crush'),
    p('nhie-spi-84', 'chosen a date spot because the lighting was flattering'),
    p('nhie-spi-85', 'had a romantic moment ruined by a ringtone'),
    p('nhie-spi-86', 'sent a good-morning text before sunrise'),
    p('nhie-spi-87', 'forgotten which story I told which date'),
    p('nhie-spi-88', 'flirted with someone in an elevator'),
    p('nhie-spi-89', 'had a date bring along an unexpected friend'),
    p('nhie-spi-90', 'used a dating-app opener copied from the internet'),
    p('nhie-spi-91', 'shared an umbrella with a stranger I liked'),
    p('nhie-spi-92', 'had a crush on someone in my trivia team'),
    p('nhie-spi-93', 'turned a group hangout into a date'),
    p('nhie-spi-94', 'made a date laugh at the worst possible moment'),
    p('nhie-spi-95', 'used a pet photo to start a conversation'),
    p('nhie-spi-96', 'worn borrowed clothes home after a night out'),
    p('nhie-spi-97', 'met someone because of a seating mix-up'),
    p('nhie-spi-98', 'had a crush notice me staring'),
    p('nhie-spi-99', 'made a toast aimed at one specific person'),
    p('nhie-spi-100', 'stayed out later because the conversation was too good'),
  ],
}
