import type { ContentPack, WstPrompt } from '@hpg/shared'

const p = (id: string, text: string): WstPrompt => ({ id, text })

/** Family tier — 100 kid-safe personal questions. */
export const wstFamily: ContentPack<WstPrompt> = {
  id: 'wst-family-v1',
  game: 'who-said-that',
  tone: 'family',
  locale: 'en',
  prompts: [
    p('wst-fam-1', 'What did you want to be when you were five?'),
    p('wst-fam-2', "What's your weirdest food combo?"),
    p('wst-fam-3', 'What would you buy first with a million dollars?'),
    p('wst-fam-4', "What's your most-used emoji?"),
    p('wst-fam-5', "What's the strangest thing you believed as a kid?"),
    p('wst-fam-6', 'If you were an animal, which one?'),
    p('wst-fam-7', 'What food could you eat every single day?'),
    p('wst-fam-8', "What's your guilty-pleasure TV show?"),
    p('wst-fam-9', 'What would you do first if you were invisible for a day?'),
    p('wst-fam-10', "What's your hidden talent?"),
    p('wst-fam-11', 'What nickname would you give yourself?'),
    p('wst-fam-12', 'Which school subject would you turn into a game?'),
    p('wst-fam-13', 'What is your perfect pizza topping?'),
    p('wst-fam-14', 'Which cartoon world would you visit?'),
    p('wst-fam-15', 'What sound always makes you laugh?'),
    p('wst-fam-16', 'What would you name a pet dragon?'),
    p('wst-fam-17', 'Which chore would you replace with a robot?'),
    p('wst-fam-18', 'What is the best smell in the world?'),
    p('wst-fam-19', 'Which color matches your personality?'),
    p('wst-fam-20', 'What is your favorite rainy-day activity?'),
    p('wst-fam-21', 'Which snack belongs in every lunchbox?'),
    p('wst-fam-22', 'What would your superhero name be?'),
    p('wst-fam-23', 'Which animal would make the funniest teacher?'),
    p('wst-fam-24', 'What is the silliest rule you would invent?'),
    p('wst-fam-25', 'Which season would you keep all year?'),
    p('wst-fam-26', 'What is your favorite thing to build?'),
    p('wst-fam-27', 'Which book character would be your friend?'),
    p('wst-fam-28', 'What is your funniest family saying?'),
    p('wst-fam-29', 'Which breakfast food wins every time?'),
    p('wst-fam-30', 'What would you put in a time capsule?'),
    p('wst-fam-31', 'Which playground game are you best at?'),
    p('wst-fam-32', 'What is your ideal snow-day plan?'),
    p('wst-fam-33', 'Which instrument would you learn instantly?'),
    p('wst-fam-34', 'What would you call a new holiday?'),
    p('wst-fam-35', 'Which vegetable deserves a better name?'),
    p('wst-fam-36', 'What is the best birthday cake flavor?'),
    p('wst-fam-37', 'Which tiny thing makes your day better?'),
    p('wst-fam-38', 'What is your best animal impression?'),
    p('wst-fam-39', 'Which room would you add to your home?'),
    p('wst-fam-40', 'What is your favorite word to say?'),
    p('wst-fam-41', 'Which toy should come to life?'),
    p('wst-fam-42', 'What job would your pet be good at?'),
    p('wst-fam-43', 'Which ice cream flavor describes you?'),
    p('wst-fam-44', 'What is your funniest school memory?'),
    p('wst-fam-45', 'Which board game piece would you redesign?'),
    p('wst-fam-46', 'What would you grow in a dream garden?'),
    p('wst-fam-47', 'Which song makes you want to dance?'),
    p('wst-fam-48', 'What is the coolest cloud shape you have seen?'),
    p('wst-fam-49', 'Which sandwich ingredient can you skip forever?'),
    p('wst-fam-50', 'What would your treehouse need most?'),
    p('wst-fam-51', 'Which family tradition do you like best?'),
    p('wst-fam-52', 'What is your favorite thing to draw?'),
    p('wst-fam-53', 'Which dinosaur matches your mood today?'),
    p('wst-fam-54', 'What is the funniest name for a boat?'),
    p('wst-fam-55', 'Which fruit makes the best snack?'),
    p('wst-fam-56', 'What would you teach an alien first?'),
    p('wst-fam-57', 'Which day of the week has the best personality?'),
    p('wst-fam-58', 'What is your favorite way to help someone?'),
    p('wst-fam-59', 'Which sport would be better on the moon?'),
    p('wst-fam-60', 'What would you order at a cloud café?'),
    p('wst-fam-61', 'Which household object would make a good mascot?'),
    p('wst-fam-62', 'What is your favorite joke punchline?'),
    p('wst-fam-63', 'Which place would you explore with a map?'),
    p('wst-fam-64', 'What would your personal flag look like?'),
    p('wst-fam-65', 'Which cookie shape tastes best?'),
    p('wst-fam-66', 'What is your go-to happy dance move?'),
    p('wst-fam-67', 'Which story should have a different ending?'),
    p('wst-fam-68', 'What would you name a new planet?'),
    p('wst-fam-69', 'Which sound effect do you make best?'),
    p('wst-fam-70', 'What is the best thing to find in your pocket?'),
    p('wst-fam-71', 'Which animal track would you follow?'),
    p('wst-fam-72', 'What would your dream parade celebrate?'),
    p('wst-fam-73', 'Which bedtime story do you remember most?'),
    p('wst-fam-74', 'Which facial expression always makes you laugh?'),
    p('wst-fam-75', 'Which snack would you make giant-sized?'),
    p('wst-fam-76', 'What would you name a friendly ghost?'),
    p('wst-fam-77', 'Which museum would you explore overnight?'),
    p('wst-fam-78', 'What is your favorite thing about weekends?'),
    p('wst-fam-79', 'Which imaginary creature would you ride?'),
    p('wst-fam-80', 'What would be in your perfect picnic?'),
    p('wst-fam-81', 'Which weather would you put in a snow globe?'),
    p('wst-fam-82', 'What is your favorite way to eat potatoes?'),
    p('wst-fam-83', 'Which famous place would you build from blocks?'),
    p('wst-fam-84', 'What would your victory cheer sound like?'),
    p('wst-fam-85', 'Which stuffed animal would lead an adventure?'),
    p('wst-fam-86', 'What is your favorite homemade treat?'),
    p('wst-fam-87', 'Which talent-show act would you perform?'),
    p('wst-fam-88', 'What would you keep in a secret clubhouse?'),
    p('wst-fam-89', 'What would you serve at a backwards dinner?'),
    p('wst-fam-90', 'What title would you give your family comedy?'),
    p('wst-fam-91', 'Which object would you shrink to pocket size?'),
    p('wst-fam-92', 'What would your dream backpack contain?'),
    p('wst-fam-93', 'Which game would you play in a castle?'),
    p('wst-fam-94', 'What is the nicest surprise you could plan?'),
    p('wst-fam-95', 'Which animal would you invite to breakfast?'),
    p('wst-fam-96', 'What would you paint on a giant mural?'),
    p('wst-fam-97', 'Which sound should a doorbell make?'),
    p('wst-fam-98', 'What is your favorite thing about your hometown?'),
    p('wst-fam-99', 'Which treat would you invent for a fair?'),
    p('wst-fam-100', 'What would the title of your adventure be?'),
  ],
}

/** Friends tier — 100 general-audience personal questions. */
export const wstFriends: ContentPack<WstPrompt> = {
  id: 'wst-friends-v1',
  game: 'who-said-that',
  tone: 'friends',
  locale: 'en',
  prompts: [
    p('wst-fri-1', "What's the most embarrassing song you love?"),
    p('wst-fri-2', "What's the dumbest way you've injured yourself?"),
    p('wst-fri-3', 'Which celebrity would you swap lives with?'),
    p('wst-fri-4', 'What was your worst fashion phase?'),
    p('wst-fri-5', "What's the strangest compliment you've received?"),
    p('wst-fri-6', 'What do you pretend to understand?'),
    p('wst-fri-7', 'Which app wastes most of your time?'),
    p('wst-fri-8', "What's a hill you'll die on?"),
    p('wst-fri-9', "What's the weirdest dream you've had recently?"),
    p('wst-fri-10', "What's your most irrational fear?"),
    p('wst-fri-11', 'What is your most questionable food opinion?'),
    p('wst-fri-12', 'Which purchase do you defend too passionately?'),
    p('wst-fri-13', 'What is your signature karaoke song?'),
    p('wst-fri-14', 'Which tiny inconvenience ruins your mood?'),
    p('wst-fri-15', 'What is your go-to excuse for being late?'),
    p('wst-fri-16', 'Which fictional character are you most like?'),
    p('wst-fri-17', 'What is the oddest item in your bag?'),
    p('wst-fri-18', 'Which trend did you regret trying?'),
    p('wst-fri-19', 'What is your most specific pet peeve?'),
    p('wst-fri-20', 'Which snack disappears fastest around you?'),
    p('wst-fri-21', 'Which browser tab is always open on your phone?'),
    p('wst-fri-22', 'Which movie quote do you use constantly?'),
    p('wst-fri-23', 'What is your funniest autocorrect mistake?'),
    p('wst-fri-24', 'Which job would you be terrible at?'),
    p('wst-fri-25', 'What is your ideal lazy Sunday?'),
    p('wst-fri-26', 'Which smell brings back a vivid memory?'),
    p('wst-fri-27', 'What is your most useless piece of trivia?'),
    p('wst-fri-28', 'Which household chore do you avoid longest?'),
    p('wst-fri-29', 'What is your comfort rewatch?'),
    p('wst-fri-30', 'Which fictional restaurant would you try?'),
    p('wst-fri-31', 'What is your most chaotic travel story?'),
    p('wst-fri-32', 'Which emoji do you use incorrectly?'),
    p('wst-fri-33', 'What is your strange but useful skill?'),
    p('wst-fri-34', 'Which celebrity would narrate your day?'),
    p('wst-fri-35', 'What is the funniest thing you believed online?'),
    p('wst-fri-36', 'Which menu item do you always order?'),
    p('wst-fri-37', 'Which shortcut do you insist is faster?'),
    p('wst-fri-38', 'Which old trend should return?'),
    p('wst-fri-39', 'What is your favorite terrible movie?'),
    p('wst-fri-40', 'Which item do you always overpack?'),
    p('wst-fri-41', 'What is your weirdest productivity trick?'),
    p('wst-fri-42', 'Which song instantly improves your mood?'),
    p('wst-fri-43', 'What is the longest grudge you held over food?'),
    p('wst-fri-44', 'Which app could you delete most easily?'),
    p('wst-fri-45', 'What is your signature party contribution?'),
    p('wst-fri-46', 'Which word do you always misspell?'),
    p('wst-fri-47', 'What is your funniest public-transport moment?'),
    p('wst-fri-48', 'Which fictional home would you move into?'),
    p('wst-fri-49', 'What is the strangest thing on your desk?'),
    p('wst-fri-50', 'Which bad habit are you oddly proud of?'),
    p('wst-fri-51', 'What is your ideal three-song road-trip lineup?'),
    p('wst-fri-52', 'Which piece of advice do you quote most?'),
    p('wst-fri-53', 'What is your most unnecessary subscription?'),
    p('wst-fri-54', 'Which fictional villain makes a fair point?'),
    p('wst-fri-55', 'What is your funniest cooking failure?'),
    p('wst-fri-56', 'Which store can you never leave empty-handed?'),
    p('wst-fri-57', 'What is the weirdest thing you collect?'),
    p('wst-fri-58', 'Which everyday task feels like an achievement?'),
    p('wst-fri-59', 'What is your default group-chat reaction?'),
    p('wst-fri-60', 'Which place has the best people-watching?'),
    p('wst-fri-61', 'What is your most repeated story?'),
    p('wst-fri-62', 'Which fashion choice defines your teenage years?'),
    p('wst-fri-63', 'What is the silliest thing you are competitive about?'),
    p('wst-fri-64', 'Which canceled plan secretly delighted you?'),
    p('wst-fri-65', 'What is your most memorable wrong turn?'),
    p('wst-fri-66', 'Which song lyric have you misunderstood for years?'),
    p('wst-fri-67', 'What is your favorite midnight snack?'),
    p('wst-fri-68', 'Which talent would make your life easier?'),
    p('wst-fri-69', 'What is the oddest gift you have kept?'),
    p('wst-fri-70', 'Which weather matches your personality?'),
    p('wst-fri-71', 'What is your funniest work-from-home moment?'),
    p('wst-fri-72', 'What would you title your memoir?'),
    p('wst-fri-73', 'What is the strangest advice you followed?'),
    p('wst-fri-74', 'Which fictional friendship resembles your own?'),
    p('wst-fri-75', 'What is your most overused phrase?'),
    p('wst-fri-76', 'Which souvenir best tells a story?'),
    p('wst-fri-77', 'What is your favorite accidental discovery?'),
    p('wst-fri-78', 'Which small luxury feels essential?'),
    p('wst-fri-79', 'What is your funniest failed surprise?'),
    p('wst-fri-80', 'Which fictional object would you borrow?'),
    p('wst-fri-81', 'What is your most controversial sandwich choice?'),
    p('wst-fri-82', 'Which routine do you refuse to change?'),
    p('wst-fri-83', 'What is the funniest nickname you have earned?'),
    p('wst-fri-84', 'Which place would you revisit tomorrow?'),
    p('wst-fri-85', 'What is your most memorable lucky break?'),
    p('wst-fri-86', 'Which competition show would you enter?'),
    p('wst-fri-87', 'What is your go-to conversation starter?'),
    p('wst-fri-88', 'Which outdated gadget do you miss?'),
    p('wst-fri-89', 'What is the funniest thing you have named?'),
    p('wst-fri-90', 'Which ordinary object best represents you?'),
    p('wst-fri-91', 'What is your most ambitious unfinished project?'),
    p('wst-fri-92', 'Which local spot would you recommend first?'),
    p('wst-fri-93', 'What ordinary place makes you feel nostalgic?'),
    p('wst-fri-94', 'Which holiday tradition would you invent?'),
    p('wst-fri-95', 'What is your favorite harmless conspiracy theory?'),
    p('wst-fri-96', 'Which photo on your phone needs explaining?'),
    p('wst-fri-97', 'What is the best bargain you ever found?'),
    p('wst-fri-98', 'Which hobby would you try with free lessons?'),
    p('wst-fri-99', 'What is your most recognizable laugh trigger?'),
    p('wst-fri-100', 'Which three words describe your weekend energy?'),
  ],
}

/** Spicy tier — 100 adult prompts; host confirms the age gate before starting. */
export const wstSpicy: ContentPack<WstPrompt> = {
  id: 'wst-spicy-v1',
  game: 'who-said-that',
  tone: 'spicy',
  locale: 'en',
  prompts: [
    p('wst-spi-1', 'Describe your worst date in one line'),
    p('wst-spi-2', "What's your most embarrassing crush?"),
    p('wst-spi-3', 'What harmless superstition do you follow before a date?'),
    p('wst-spi-4', "What's the pettiest reason you rejected someone?"),
    p('wst-spi-5', "What's the worst pickup line you've used or received?"),
    p('wst-spi-6', "Who's your celebrity hall pass?"),
    p('wst-spi-7', 'What weather mishap made a date unexpectedly funny?'),
    p('wst-spi-8', 'What have you done to impress a crush?'),
    p('wst-spi-9', 'What harmless dating habit do your friends tease you about?'),
    p('wst-spi-10', 'Describe your ideal date in exactly three words'),
    p('wst-spi-11', 'What is your signature flirting move?'),
    p('wst-spi-12', 'Which dating-app opener actually worked on you?'),
    p('wst-spi-13', 'What is your most memorable first-date outfit?'),
    p('wst-spi-14', 'Which celebrity was your first grown-up crush?'),
    p('wst-spi-15', 'What is the funniest excuse you used to leave a date?'),
    p('wst-spi-16', 'Which song belongs on your romance soundtrack?'),
    p('wst-spi-17', 'What is the boldest first message you have sent?'),
    p('wst-spi-18', 'Which famous landmark would make an overrated date spot?'),
    p('wst-spi-19', 'What is your most awkward flirting moment?'),
    p('wst-spi-20', 'Which date-night food should be banned?'),
    p('wst-spi-21', 'What is the sweetest surprise someone planned for you?'),
    p('wst-spi-22', 'Which trait makes you instantly interested?'),
    p('wst-spi-23', 'What is your funniest dating-profile photo story?'),
    p('wst-spi-24', 'Which romantic gesture would win you over?'),
    p('wst-spi-25', 'What is the worst date location you have tried?'),
    p('wst-spi-26', 'Which outfit makes you feel most confident?'),
    p('wst-spi-27', 'What is the most obvious hint you completely missed?'),
    p('wst-spi-28', 'Which fictional couple should break up?'),
    p('wst-spi-29', 'What is your favorite harmless dating deal-breaker?'),
    p('wst-spi-30', 'Which compliment makes you blush fastest?'),
    p('wst-spi-31', 'What is your most dramatic post-date debrief?'),
    p('wst-spi-32', 'Which dance move do you attempt on a night out?'),
    p('wst-spi-33', 'What is the funniest name saved in your contacts?'),
    p('wst-spi-34', 'Which bar snack best describes your dating style?'),
    p('wst-spi-35', 'What is your most memorable meet-cute?'),
    p('wst-spi-36', 'Which romantic movie moment would you recreate?'),
    p('wst-spi-37', 'What is your funniest restaurant-ordering mistake on a date?'),
    p('wst-spi-38', 'Which quality do you notice first in someone?'),
    p('wst-spi-39', 'What is your funniest accidental date?'),
    p('wst-spi-40', 'What topic saved your most awkward first-date silence?'),
    p('wst-spi-41', 'What is your ideal low-budget date?'),
    p('wst-spi-42', 'Which song would ruin a romantic moment?'),
    p('wst-spi-43', 'What is the most confusing signal you have received?'),
    p('wst-spi-44', 'Which friend gives the wildest dating advice?'),
    p('wst-spi-45', 'What is your favorite flirty emoji?'),
    p('wst-spi-46', 'Which date story do your friends retell most?'),
    p('wst-spi-47', 'What is the pettiest dating-app swipe decision you made?'),
    p('wst-spi-48', 'Which nickname from a partner made you laugh?'),
    p('wst-spi-49', 'What is your ideal last-minute date plan?'),
    p('wst-spi-50', 'Which romantic cliché secretly works on you?'),
    p('wst-spi-51', 'What is the funniest way someone asked for your number?'),
    p('wst-spi-52', 'Which night-out story needs a one-line warning label?'),
    p('wst-spi-53', 'What is your biggest green flag on a first date?'),
    p('wst-spi-54', 'Which song have you dedicated to a crush?'),
    p('wst-spi-55', 'What is your funniest attempt to look mysterious?'),
    p('wst-spi-56', 'Which harmless dating convention do you happily ignore?'),
    p('wst-spi-57', 'What is the strangest date invitation you accepted?'),
    p('wst-spi-58', 'Which reality-show date would you choose?'),
    p('wst-spi-59', 'What is your most questionable night-out purchase?'),
    p('wst-spi-60', 'Which romantic nickname would you refuse?'),
    p('wst-spi-61', 'What is your funniest almost-kiss interruption?'),
    p('wst-spi-62', 'Which city would host your perfect date?'),
    p('wst-spi-63', 'What is the boldest compliment you have given?'),
    p('wst-spi-64', 'Which detail made a bad date unforgettable?'),
    p('wst-spi-65', 'What is your ideal flirty text in three words?'),
    p('wst-spi-66', 'Which friend would write your dating profile best?'),
    p('wst-spi-67', 'What is your funniest mistaken-identity flirtation?'),
    p('wst-spi-68', 'Which snack fuels your best night-out stories?'),
    p('wst-spi-69', 'What is the most romantic thing you have cooked?'),
    p('wst-spi-70', 'Which dance-floor song reveals your true personality?'),
    p('wst-spi-71', 'What is your most memorable dating-app bio line?'),
    p('wst-spi-72', 'Which fictional date would be a complete disaster?'),
    p('wst-spi-73', 'What is the funniest thing you carried on a date?'),
    p('wst-spi-74', 'Which personality trait gets you into romantic trouble?'),
    p('wst-spi-75', 'What is your ideal spontaneous weekend invitation?'),
    p('wst-spi-76', 'Which date-night activity brings out your competitive side?'),
    p('wst-spi-77', 'What is the cheekiest note you have received?'),
    p('wst-spi-78', 'Which famous voice would read your love letters?'),
    p('wst-spi-79', 'What is your funniest overthinking-a-text story?'),
    p('wst-spi-80', 'Which romantic tradition would you invent?'),
    p('wst-spi-81', 'What is the most dramatic entrance you made on a night out?'),
    p('wst-spi-82', 'Which first-date question tells you the most?'),
    p('wst-spi-83', 'What is your funniest friend-arranged setup?'),
    p('wst-spi-84', 'Which love song lyric makes you roll your eyes?'),
    p('wst-spi-85', 'What is the strangest item you brought home after a night out?'),
    p('wst-spi-86', 'Which fictional bar would be your regular spot?'),
    p('wst-spi-87', 'What is your boldest vacation-romance memory?'),
    p('wst-spi-88', 'Which innocent phrase sounds flirty when you say it?'),
    p('wst-spi-89', 'What is your most creative second-date idea?'),
    p('wst-spi-90', 'Which photo would you never use on a dating profile?'),
    p('wst-spi-91', 'What is the funniest way a date misread the room?'),
    p('wst-spi-92', 'Which detail makes a night out feel special?'),
    p('wst-spi-93', 'What is your favorite story about meeting someone new?'),
    p('wst-spi-94', 'Which romantic gift would confuse you most?'),
    p('wst-spi-95', 'What is the most confident thing you have done for a crush?'),
    p('wst-spi-96', 'Which late-night food completes a great date?'),
    p('wst-spi-97', 'What is your funniest date-ending line?'),
    p('wst-spi-98', 'Which tiny gesture feels unexpectedly romantic?'),
    p('wst-spi-99', 'What silly trophy would you award your dating history?'),
    p('wst-spi-100', 'Which three words describe your flirting style?'),
  ],
}
