import type { ContentPack, WyrPrompt } from '@hpg/shared'

/**
 * Family tier — kid-safe, no romance/relationship content. 100 prompts.
 */
export const wyrFamily: ContentPack<WyrPrompt> = {
  id: 'wyr-family-v1',
  game: 'would-you-rather',
  tone: 'family',
  locale: 'en',
  prompts: [
    { id: 'wyr-fam-1', a: 'Be able to fly', b: 'Be able to turn invisible' },
    { id: 'wyr-fam-2', a: 'Talk to animals', b: 'Speak every human language' },
    { id: 'wyr-fam-3', a: 'Never do homework again', b: 'Never do chores again' },
    { id: 'wyr-fam-4', a: 'Live in a treehouse', b: 'Live in a castle' },
    { id: 'wyr-fam-5', a: 'Only eat pizza forever', b: 'Only eat ice cream forever' },
    { id: 'wyr-fam-6', a: 'Have a pet dragon', b: 'Have a pet dinosaur' },
    {
      id: 'wyr-fam-7',
      a: 'Be 10 minutes early everywhere',
      b: 'Get 10 extra minutes of sleep daily',
    },
    {
      id: 'wyr-fam-8',
      a: 'Have a trampoline floor at home',
      b: 'Have a waterslide instead of stairs',
    },
    {
      id: 'wyr-fam-9',
      a: 'Always have to sing instead of talk',
      b: 'Always have to dance while walking',
    },
    { id: 'wyr-fam-10', a: 'Visit the past', b: 'Visit the future' },
    ...wyr('fam', 11, [
      ['Explore outer space', 'Explore the deep ocean'],
      ['Have a robot helper', 'Have a magical backpack'],
      ['Breathe underwater', 'Walk through walls'],
      ['Eat only crunchy food', 'Eat only soft food'],
      ['Control the weather', 'Control time for one minute daily'],
      ['Ride a giant eagle', 'Sail a friendly whale'],
      ['Have a room made of pillows', 'Have a backyard full of trampolines'],
      ['Be the fastest runner', 'Be the strongest swimmer'],
      ['Find buried treasure', 'Discover a new planet'],
      ['Have pancakes for every breakfast', 'Have tacos for every dinner'],
      ['Shrink to ant size', 'Grow as tall as a building'],
      ['Always know the answer', 'Always know the best question'],
      ['Build the best snow fort', 'Build the best sandcastle'],
      ['Have a tail like a monkey', 'Have ears like an elephant'],
      ['Spend a day in a video game', 'Spend a day in a storybook'],
      ['Make plants grow instantly', 'Make broken toys repair themselves'],
      ['Wear pajamas everywhere', 'Wear a costume everywhere'],
      ['Have a library in your bedroom', 'Have an arcade in your basement'],
      ['Meet an alien', 'Meet a mermaid'],
      ['Jump as high as a house', 'Run as fast as a train'],
      ['Need only one hour of sleep', 'Need only one meal a day'],
      ['Be great at every sport', 'Play every instrument'],
      ['Live where it always snows', 'Live where it is always summer'],
      ['Have popcorn rain', 'Have bubble snow'],
      ['Remember everything you read', 'Draw anything perfectly'],
      ['Travel by hot-air balloon', 'Travel by submarine'],
      ['Have a tiny elephant', 'Have a giant hamster'],
      ['Eat every meal with chopsticks', 'Eat every meal with a tiny spoon'],
      ['Find a secret tunnel at home', 'Find a hidden room at school'],
      ['Be captain of a pirate ship', 'Be pilot of a spaceship'],
      ['Have glowing hair', 'Have color-changing eyes'],
      ['Always win board games', 'Always win scavenger hunts'],
      ['Make anyone laugh', 'Cheer anyone up'],
      ['Talk to trees', 'Talk to clouds'],
      ['Have a week without screens', 'Have a week without sweets'],
      ['Climb any wall', 'Balance on any surface'],
      ['Visit a chocolate factory', 'Visit a toy factory'],
      ['Have shoes that let you hover', 'Have gloves that give super strength'],
      ['Be a wizard for a day', 'Be a superhero for a day'],
      ['Know every magic trick', 'Know every joke'],
      ['Live beside a waterfall', 'Live beside a volcano'],
      ['Have a personal theme song', 'Have your own cheering crowd'],
      ['Never lose a sock', 'Never step on a toy'],
      ['Sleep in a hammock', 'Sleep in a blanket fort'],
      ['Create a new holiday', 'Invent a new sport'],
      ['Race a cheetah', 'Swim beside a dolphin'],
      ['Have a pencil that draws real things', 'Have a book that answers questions'],
      ['Be excellent at cooking', 'Be excellent at building'],
      ['Spend recess on the moon', 'Take a field trip to a castle'],
      ['Have a treehouse village', 'Have an underground clubhouse'],
      ['Only communicate with rhymes', 'Only communicate with drawings'],
      ['Get one huge present yearly', 'Get one tiny present weekly'],
      ['Have a friendly ghost roommate', 'Have a friendly robot roommate'],
      ['Eat a super-sour snack', 'Eat a super-spicy snack'],
      [
        'Leave sparkling footprints wherever you walk',
        'Leave glowing handprints on everything you touch',
      ],
      ['See in the dark', 'See through solid walls'],
      ['Have wheels instead of feet', 'Have springs instead of legs'],
      ['Lead a parade', 'Star in a circus'],
      ['Wake up with colorful feathers', 'Wake up with twitchy whiskers'],
      ['Have a backyard maze', 'Have a backyard mini-golf course'],
      ['Paint the sky at sunset', 'Name every star'],
      ['Be able to pause dreams', 'Choose what you dream about'],
      ['Have a snow day every month', 'Have a three-day weekend every month'],
      ['Wear flippers all day', 'Wear mittens all day'],
      ['Make one wish for yourself', 'Make three wishes for others'],
      ['Be the funniest person', 'Be the most creative person'],
      ['Explore a jungle temple', 'Explore an ice cave'],
      ['Have a lunchbox that refills', 'Have pockets that hold anything'],
      ['Master one hard skill instantly', 'Learn any skill twice as fast'],
      ['Have a pet that can talk', 'Have a toy that comes alive'],
      ['Live without music', 'Live without movies'],
      ['Always smell cookies', 'Always hear birds singing'],
      ['Play in a giant ball pit', 'Bounce in a giant inflatable castle'],
      ['Have a map to every hidden place', 'Have a key that opens every door'],
      ['Be friends with a giant', 'Be friends with a fairy'],
      ['Only read comics', 'Only watch cartoons'],
      ['Make a perfect paper airplane', 'Make an unbreakable soap bubble'],
      ['Have unlimited craft supplies', 'Have unlimited building blocks'],
      ['Spend a day as a cat', 'Spend a day as a dog'],
      ['Have an extra hour of playtime', 'Have an extra hour of sleep'],
      ['Be known for bravery', 'Be known for kindness'],
      ['Live on a houseboat', 'Live in a mountain cabin'],
      ['Turn any floor into ice', 'Turn any chair into a swing'],
      ['Win a spelling bee', 'Win a science fair'],
      ['Have a garden of giant flowers', 'Have an orchard of tiny trees'],
      ['Visit every national park', 'Visit every great museum'],
      ['Never get a paper cut', 'Never get tangled shoelaces'],
      ['Have an indoor pool', 'Have an outdoor movie screen'],
      ['Know what animals are thinking', 'Know what babies are thinking'],
      ['Be able to fold anything into origami', 'Build anything from cardboard'],
    ]),
  ],
}

/** Friends tier — general audience, mildly cheeky. 100 prompts. */
export const wyrFriends: ContentPack<WyrPrompt> = {
  id: 'wyr-friends-v1',
  game: 'would-you-rather',
  tone: 'friends',
  locale: 'en',
  prompts: [
    { id: 'wyr-fri-1', a: 'Always be 10 minutes late', b: 'Always be 20 minutes early' },
    { id: 'wyr-fri-2', a: 'Free flights for life', b: 'Free food for life' },
    { id: 'wyr-fri-3', a: 'Lose your phone for a month', b: 'Lose your wallet every week' },
    {
      id: 'wyr-fri-4',
      a: 'Always say exactly what you think',
      b: 'Never be able to complain again',
    },
    { id: 'wyr-fri-5', a: 'Be famous but always broke', b: 'Be rich but totally unknown' },
    { id: 'wyr-fri-6', a: 'Have your group chat leaked', b: 'Have your search history leaked' },
    { id: 'wyr-fri-7', a: 'Re-live one year of your life', b: 'Skip one year into the future' },
    { id: 'wyr-fri-8', a: 'Never wait in line again', b: 'Never hit traffic again' },
    { id: 'wyr-fri-9', a: 'Only whisper forever', b: 'Only shout forever' },
    { id: 'wyr-fri-10', a: 'Fight one horse-sized duck', b: 'Fight a hundred duck-sized horses' },
    ...wyr('fri', 11, [
      ['Give up streaming for a year', 'Give up social media for a year'],
      ['Always choose the restaurant', 'Never choose the restaurant'],
      ['Know every spoiler', 'Never know how anything ends'],
      ['Have unlimited coffee', 'Have unlimited takeout'],
      ['Work four long days', 'Work six short days'],
      ['Travel alone', 'Travel with a chaotic group'],
      ['Live beside your best friends', 'Live in your dream city'],
      ['Be overdressed everywhere', 'Be underdressed everywhere'],
      ['Host every gathering', 'Plan every trip'],
      ['Have perfect memory', 'Forget every embarrassing moment'],
      ['Only send voice notes', 'Only make phone calls'],
      ['Share a tiny city apartment', 'Live alone far from everything'],
      ['Get free concert tickets', 'Get free sports tickets'],
      ['Always find parking', 'Always get the best table'],
      ['Be great at small talk', 'Be great at telling stories'],
      ['Give up caffeine', 'Give up dessert'],
      ['Have a personal chef', 'Have a personal cleaner'],
      ['Take a dream vacation now', 'Take three good vacations later'],
      ['Know your future career', 'Know your future home'],
      ['Redo your first day at work', 'Redo your first day of school'],
      ['Only watch new movies', 'Only rewatch favorites'],
      ['Live by the beach', 'Live in the mountains'],
      ['Have one loyal friend nearby', 'Have many friends worldwide'],
      ['Be the designated driver', 'Be the designated planner'],
      ['Lose every charger', 'Crack every phone screen'],
      ['Have perfect Wi-Fi', 'Have perfect cell service'],
      ['Cook every meal', 'Wash every dish'],
      ['Attend every wedding', 'Attend every reunion'],
      ['Read minds for ten seconds', 'See ten minutes into the future'],
      ['Always split the bill evenly', 'Always calculate every exact share'],
      ['Have a year of weekends', 'Have a month of dream travel'],
      ['Be unable to use emojis', 'Be unable to use punctuation'],
      ['Know every local secret spot', 'Know the best place in every city'],
      ['Give a speech unprepared', 'Sing karaoke alone'],
      ['Have unlimited books', 'Have unlimited games'],
      ['Live above a noisy café', 'Live below a tap dancer'],
      ['Be a brilliant cook', 'Be a brilliant conversationalist'],
      ['Delete every old photo', 'Delete every old message'],
      ['Always get aisle seats', 'Always get window seats'],
      ['Wear one color forever', 'Wear a different color daily'],
      ['Own a vacation home', 'Take a luxury trip yearly'],
      ['Meet your favorite artist', 'Meet your favorite athlete'],
      ['Have plans every Friday', 'Have every Friday free'],
      ['Only eat at restaurants', 'Only eat home cooking'],
      ['Know when someone is bluffing', 'Never be caught bluffing'],
      ['Repeat your best year', 'Erase your worst year'],
      ['Have a job you love with modest pay', 'Have a dull job with excellent pay'],
      ['Be respected by everyone', 'Be understood by your closest people'],
      ['Always have exact change', 'Always have a charged phone'],
      ['Lose access to maps', 'Lose access to calendars'],
      ['Be stuck in an elevator with coworkers', 'Be stuck at an airport with relatives'],
      ['Only take red-eye flights', 'Only drive through rush hour'],
      ['Have your life narrated', 'Have a laugh track follow you'],
      ['Sit through a boring encore', 'Miss the opening of an amazing show'],
      ['Plan a surprise party', 'Be surprised by a party'],
      ['Have a signature outfit', 'Have a signature catchphrase'],
      ['Live with no air conditioning', 'Live with no heating'],
      ['Always forget names', 'Always forget faces'],
      ['Have a rewind button', 'Have a mute button'],
      ['Win every trivia night', 'Win every game night'],
      ['Share every playlist', 'Share every photo album'],
      ['Only drink hot beverages', 'Only drink iced beverages'],
      ['Spend a rainy weekend camping', 'Spend a sunny weekend working'],
      ['Have a rooftop garden', 'Have a basement theater'],
      ['Take one perfect photo', 'Take one hundred funny photos'],
      ['Never use delivery apps', 'Never use ride-share apps'],
      ['Be known for honesty', 'Be known for diplomacy'],
      ['Always have a clever comeback', 'Never need to defend yourself'],
      ['Get a surprise day off', 'Get a surprise travel upgrade'],
      ['Only attend huge parties', 'Only attend tiny dinners'],
      ['Remember every dream', 'Control one dream each week'],
      ['Have unlimited closet space', 'Have unlimited kitchen space'],
      ['Spend a year abroad', 'Spend a year near family'],
      ['Be excellent at directions', 'Be excellent at time management'],
      ['Swap lives with a friend for a week', 'Swap jobs with a stranger for a month'],
      ['Never hear gossip', 'Hear gossip but never repeat it'],
      ['Own fewer perfect things', 'Own many useful things'],
      ['Have a permanent three-day weekend', 'Have two months off yearly'],
      ['Always pick the winning team', 'Always predict the plot twist'],
      ['Lose your keys weekly', 'Forget one password daily'],
      ['Have a quiet neighbor', 'Have a helpful landlord'],
      ['Only communicate in memes', 'Only communicate in song lyrics'],
      ['Get front-row seats', 'Get backstage access'],
      ['Always give honest advice', 'Always give comforting advice'],
      ['Live in your hometown forever', 'Move somewhere new every two years'],
      ['Have a famous podcast', 'Write a bestselling book'],
      ['Always know what to order', 'Always know what to wear'],
      ['Own a tiny home in your ideal neighborhood', 'Own a large home far from everything'],
      ['Have every meeting be useful', 'Have every commute be peaceful'],
      ['Be the funniest in the room', 'Be the wisest in the room'],
    ]),
  ],
}

/** Spicy tier — 18+ only; host confirms the age gate before starting. 100 prompts. */
export const wyrSpicy: ContentPack<WyrPrompt> = {
  id: 'wyr-spicy-v1',
  game: 'would-you-rather',
  tone: 'spicy',
  locale: 'en',
  prompts: [
    {
      id: 'wyr-spi-1',
      a: 'Have every first date critiqued afterward',
      b: 'Have every flirting attempt scored afterward',
    },
    { id: 'wyr-spi-2', a: 'Get back with an ex', b: 'Stay single for five years' },
    { id: 'wyr-spi-3', a: 'Date someone 15 years older', b: 'Date someone your parents pick' },
    { id: 'wyr-spi-4', a: 'Accidentally text your crush', b: 'Accidentally text your boss' },
    { id: 'wyr-spi-5', a: 'Know who has a crush on you', b: 'Know what your ex says about you' },
    {
      id: 'wyr-spi-6',
      a: 'Have friends choose every first-date location',
      b: 'Have relatives choose every first-date outfit',
    },
    { id: 'wyr-spi-7', a: 'Never flirt again', b: 'Flirt with everyone, always, badly' },
    { id: 'wyr-spi-8', a: 'Marry rich without love', b: 'Marry broke with love' },
    { id: 'wyr-spi-9', a: 'Have every date livestreamed', b: 'Have your mom on every first date' },
    {
      id: 'wyr-spi-10',
      a: 'Have a crush hear about your feelings from a stranger',
      b: 'Have an ex mistakenly think you want them back',
    },
    ...wyr('spi', 11, [
      ['Have a terrible first date', 'Have an awkward second date'],
      ['Wait three days for an amazing reply', 'Get an instant but boring reply'],
      ['Date someone too similar', 'Date someone completely opposite'],
      ['Reveal your celebrity crush', 'Reveal your first crush'],
      ['Have food stuck in your teeth through a date', 'Have your shirt inside out through a date'],
      ['Make the first move', 'Wait and risk missing the chance'],
      ['Meet a perfect match far away', 'Meet an imperfect match next door'],
      ['Spill sauce across a first-date table', 'Send an appetizer flying across the room'],
      ['Have chemistry without shared interests', 'Share interests without instant chemistry'],
      ['Attend an ex’s wedding', 'Invite an ex to your wedding'],
      ['Get seated beside an ex on a date', 'Get seated beside your boss on a date'],
      ['Go on a silent first date', 'Go on a phone-free first date'],
      ['Be remembered for a bad joke', 'Be forgotten after a great date'],
      ['Have a crush know immediately', 'Never know whether they noticed'],
      ['Arrive an hour early for a date', 'Have a date arrive an hour late'],
      ['Receive an over-the-top compliment', 'Give an over-the-top compliment'],
      ['Have an awkward kiss story shared', 'Have an awkward date story shared'],
      ['Only date through introductions', 'Only date through apps'],
      ['Choose romance without adventure', 'Choose adventure without romance'],
      ['Have your ex become famous', 'Have your crush become famous'],
      ['Plan every date', 'Never know the date plan'],
      ['Wear matching outfits on dates', 'Use matching profile pictures'],
      ['Have amazing banter by text', 'Have amazing chemistry in person'],
      ['Have the karaoke microphone squeal mid-flirt', 'Trip during a slow dance with a crush'],
      [
        'Flirt with the wedding photographer',
        'Flirt with someone you mistake for the wedding planner',
      ],
      [
        'Mispronounce a date’s name all night',
        'Realize a date has mispronounced your name all night',
      ],
      [
        'Have friends recognize your date from an awkward story',
        'Have family mistake your date for someone else',
      ],
      ['Share your worst pickup line', 'Share your worst rejection'],
      ['Go on three short dates', 'Go on one all-day date'],
      ['Date someone with no social media', 'Date someone who posts everything'],
      ['Know why every date ended', 'Know what every date really thought'],
      ['Be charming but clumsy', 'Be mysterious but awkward'],
      ['Receive flowers at work', 'Receive a love note in public'],
      ['Have a public proposal', 'Have a private proposal'],
      ['Revisit your first-date location', 'Recreate your best date'],
      [
        'Wear the same outfit as your ex’s new date',
        'Compliment a stranger you mistake for your date',
      ],
      ['Run into coworkers during a date', 'Have relatives seated at the next table'],
      ['Share a playlist too soon', 'Share a pet name too soon'],
      ['Have one unforgettable romance', 'Have many fun short romances'],
      ['Flirt only face-to-face', 'Flirt only through messages'],
      ['Date someone who steals the blankets', 'Date someone who steals your fries'],
      ['Say “I like you” first', 'Ask “what are we?” first'],
      ['Have a date meet your friends early', 'Meet their friends early'],
      [
        'Endure a cheesy serenade in a crowded restaurant',
        'Be caught lip-syncing a love song to a mirror',
      ],
      ['Be caught rehearsing a text', 'Be caught practicing a compliment'],
      ['Have your dating app bio read aloud', 'Have your old captions read aloud'],
      ['Take a romantic road trip', 'Take a romantic city break'],
      ['Date someone with perfect style', 'Date someone with perfect humor'],
      ['Be ghosted after one date', 'Be slowly faded after three'],
      ['Accidentally like an old photo', 'Accidentally send a screenshot'],
      ['Have a crush at work', 'Have a crush in your friend group'],
      ['Choose butterflies', 'Choose dependable calm'],
      ['Have a date who talks too much', 'Have a date who barely talks'],
      ['Share dessert', 'Share a playlist'],
      ['Get caught flirting badly', 'Miss obvious flirting entirely'],
      ['Date someone who plans months ahead', 'Date someone who plans an hour ahead'],
      ['Relive your funniest date', 'Erase your most awkward date'],
      ['Have an excellent date in a bad place', 'Have a bad date in an excellent place'],
      ['Reveal your type', 'Reveal your biggest dating turnoff'],
      ['Date someone very competitive', 'Date someone who never chooses'],
      ['Have a perfect meet-cute', 'Have a hilarious dating story'],
      ['Receive ten casual compliments', 'Receive one unforgettable compliment'],
      ['Be introduced as “a friend”', 'Introduce someone as “a friend”'],
      ['Meet the right person too early', 'Meet them later than hoped'],
      [
        'Have a cartoon ringtone interrupt a flirt',
        'Have a squeaky shoe announce every step past a crush',
      ],
      ['Have your date’s pet dislike you', 'Have your pet like your date more than you'],
      [
        'Expect a private date and find a surprise party',
        'Expect a private date and find a surprise double-date',
      ],
      ['Be teased about your crush', 'Tease your crush by accident'],
      ['Have friends see your first date', 'Have coworkers see your first date'],
      ['Only receive bold messages', 'Only receive mysterious messages'],
      ['Admit jealousy', 'Admit nervousness'],
      ['Date someone with an embarrassing nickname', 'Have them learn yours'],
      ['Fall for a longtime friend', 'Fall for someone you just met'],
      ['Have a date critique your playlist', 'Have a date critique your outfit'],
      ['Share your most-used dating emoji', 'Share your most-used flirting phrase'],
      ['Have the perfect date end early', 'Have an average date last all night'],
      ['Meet someone while looking messy', 'Meet someone while acting awkward'],
      [
        'Remember every detail except a date’s name',
        'Remember only the date’s most awkward moment',
      ],
      ['Receive a baffling handmade gift', 'Receive an oversized gift on a first date'],
      ['Have your crush read your notes app', 'Have your crush see your saved posts'],
      [
        'Have friends narrate your flirting like a sport',
        'Have family narrate your date like a documentary',
      ],
      ['Be the one who blushes', 'Be the one who causes blushing'],
      ['Go on a date with no conversation topics', 'Go on a date with no plan'],
      ['Have one mutual crush revealed', 'Have three secret admirers stay unknown'],
      [
        'Sleep through a flirty 2 a.m. message',
        'Hear a flirty voice note before your morning coffee',
      ],
      ['Be asked out in front of friends', 'Ask someone out in front of friends'],
      [
        'Have a date mistake dinner for a proposal',
        'Have a server mistake friendship for an anniversary',
      ],
      ['Keep old love letters', 'Keep old date photos'],
      ['Know your best match today', 'Meet your best match unexpectedly'],
      ['Be unforgettable for your confidence', 'Be unforgettable for your humor'],
    ]),
  ],
}

function wyr(tone: 'fam' | 'fri' | 'spi', start: number, choices: [string, string][]): WyrPrompt[] {
  return choices.map(([a, b], index) => ({ id: `wyr-${tone}-${start + index}`, a, b }))
}
